deploy/examples/docker-compose/down.sh, deploy/examples/docker-compose/up.sh
Update deployment example scripts.
Update deployment example scripts.
None.
Local test.
=> chore: update deployment example scripts

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/Constants.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/GaeaSqlTaskUtil.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/listener/CustomPluginUpdateListener.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/LogPlugin.java
=> feat(home): config timezone column (#142)

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/date/TimeFilter.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/emuns/FunctionEnum.java, server/home/home-boot/src/main/java/io/holoinsight/server/home/bootstrap/HoloinsightHomeConfiguration.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/MarketplacePlugin.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/MarketplaceProduct.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/dto/MarketplacePluginDTO.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/dto/MarketplaceProductDTO.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/DefaultMarketplaceProductHandler.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/MarketplaceProductHandler.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmGroupFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/MarketplacePluginFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/MarketplaceProductFacadeImpl.java
Closes #144 
* Add `version` field to `MarketplaceProduct` and `MarketplacePlugin`
* Add `MarketplaceProductHandler` interface to handle  installation and uninstallation of `MarketplaceProduct`
* Provide default implement `DefaultMarketplaceProductHandler ` for `MarketplaceProductHandler`
None.
Local test.
=> feat(home): marketplace product of hosting alert

server/query/query-common/src/main/java/io/holoinsight/server/query/common/RpnResolver.java, server/query/query-service/src/main/java/io/holoinsight/server/query/service/impl/DefaultQueryServiceImpl.java, server/storage/storage-server/storage-receiver/src/main/java/io/holoinsight/server/storage/receiver/trace/SpanHandler.java
Closes #
- Add a log to record the reporting status of the span;
- Throw the exception of RpnResolver, and look forward to supplementing the missing data through fill-data.
Related source files are changed.
None.
CI passed.
=> feat: log trace report; optimize complex failed and data filling;

server/query/query-service/src/main/java/io/holoinsight/server/query/service/impl/DefaultQueryServiceImpl.java
Closes #
Fix the problem of repeatedly querying data sources in complex queries.
DefaultQueryServiceImpl.java has been changed.
None.
CI passed.
=> fix: remove redundant queries in complex-query

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/GaeaSqlTaskUtil.java
Closes #148 
add time format layout type yyyy-MM-ddTHH:mm:ss 
GaeaSqlTaskUtil
while setting the time column , yyyy-MM-ddTHH:mm:ss  will be supported 
CI
=> feat(home): add time format layout: yyyy-MM-ddTHH:mm:ss (#148)

README-CN.md
None.
Not involved.
README-CN.md
No.
No need.
=> docs: add community info into readme-cn

server/common/common-dao/src/main/java/io/holoinsight/server/common/dao/entity/MetaDataDictValue.java, server/common/common-dao/src/main/java/io/holoinsight/server/common/dao/mapper/MetaDataDictValueMapper.java, server/common/common-service/src/main/java/io/holoinsight/server/common/service/CommonServiceAutoConfiguration.java, server/common/common-service/src/main/java/io/holoinsight/server/common/service/MetaDataDictValueService.java, server/common/common-service/src/main/java/io/holoinsight/server/common/service/MetaDataDictValueServiceImpl.java, server/common/common-service/src/main/java/io/holoinsight/server/common/service/MetaDictValueService.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AlgorithmHttp.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/data/load/AIAlarmLoadData.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/CacheAlertConfig.java, server/home/home-boot/src/main/java/io/holoinsight/server/home/bootstrap/HoloinsightHomeConfiguration.java, server/home/home-service/pom.xml, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictUtil.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/SuperCache.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/SuperCacheService.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/MetaDataDictValueFacadeImpl.java
Closes #153 
1. put metadata_dictvalue table in io.holoinsight.server.common moudle
2. move the MetaDictValueService into this module.
3. modify the call implementation inside SuperCacheService 
4. add CommonServiceAutoConfiguration to the startup dependency of the home module
5. add MetaDataDictValueFacadeImpl webapi in the home module
=> feat: put the metadata_dictvalue table in common module

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlertRuleServiceImpl.java
Alert rule can be searched by fuzzy matching `source_type`.
e2e
=> feat(home): alert rule query by fuzzy matching

README.md
Add product documentation links
Add product documentation links
No
=> docs: add product documentation links

server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlarmRuleDTO.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/NotificationTemplate.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmRuleFacadeImpl.java
- Fix source link url for alert notification;
- In markdown mode alert notification, the tag of the timeline is displayed as an unordered list.
There will be some changes to the markdown alert notification.
e2e.
=> feat(home): optimize notification template

deploy/examples/docker-compose/docker-compose.yaml, deploy/examples/docker-compose/down.sh, deploy/examples/docker-compose/up.sh
Closes #170 
'Quick Start' demo use arm64v8 image in M1 mac.
'Quick Start' demo use arm64v8 image in M1 mac.
The build script of arm64 image will be submitted in another PR.
Local test.
=> fix: quick start demo use arm64v8 image in M1 mac

deploy/examples/docker-compose/down.sh, deploy/examples/docker-compose/up.sh
Closes #175 
Use another way to fetch realpath
Use another way to fetch realpath
No
Local test
=> fix: use another way to fetch realpath

.github/workflows/build.yml, .github/workflows/integration-testing.yml, deploy/examples/docker-compose/install-agent.sh, deploy/examples/docker-compose/up.sh
Closes #167 
Add base preparation (a Github Actions workflow) for integration tests. 
Add a Github Actions workflow for integration tests.  
The job will build server docker image and deploy all dependencies and server using docker-compose.  
Then we need to gradually add integration tests in the next few PRs.
No
Github Actions.
=> ci: add integration test basis using Github Actions

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AbstractUniformInspectRunningRule.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AlertTaskCompute.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AlgorithmHttp.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/dto/IntegrationPluginDTO.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlarmRuleDTO.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/TemplateValue.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/listener/CustomPluginUpdateListener.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmRuleFacadeImpl.java
Closes #197 
- Thread pool is used in `runRule` and `calculate`.
- Fix the resolution for alert source link.
None.
Local test.
=> feat(home): alert compute thread pool

server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/grpc/RegistryServerForAgent.java
Closes #
Default 'maxInboundMessageSize' of registry grpc server is 4MB, which is too small when `clusteragent` invoke a full metadata sync containing all pods in a k8s cluster.
I update this option to 64MB.
Set 'maxInboundMessageSize' of registry grpc server to 64MB
No
Local test
=> chore(registry): Set 'maxInboundMessageSize' of registry grpc server to 64MB

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AlertTaskCompute.java
Closes #207 
The cause of the problem is the time to do filtering with alert events, the calculation is not over yet, so the ArrayList throw ConcurrentModificationException.
- Using CountDownLatch in `calculate` method.
None.
Local test.
=> fix(home): ConcurrentModificationException in alert

server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmRuleFacadeImpl.java
- Add holoinsight link in alert notification.
- Enhance the alert rule query api. 
- Alert link need **parentId** parameter in GET path, like `https://holoinsight.***.com/log/metric/150?parentId=71`
- `/querySubscribeList` and `/querySubAlarmHistory` add the `myself` parameter to query the self-created alert rules
Users can query alert rules that are created by themselves.
Local test.
=> fix(home): fix alert link

README-CN.md, README.md
Closes #
Add links to holoinsight-docs website
Add links to holoinsight-docs website
No
=> docs: add links to holoinsight-docs website

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/config/LogPluginConfig.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/AbstractIntegrationPlugin.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/JvmPlugin.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/LogPlugin.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/MultiLogPlugin.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/OceanBasePlugin.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/PortCheckPlugin.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/SpringBootPlugin.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/TenantIntegrationGeneratedTask.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AgentFacadeImpl.java
Closes #220 
1. Support for multiple logging templates in _LogPlugin_
2. Append the definition of the monitor item name in all IntegrationPlugins
3. Update _TenantIntegrationGeneratedTask_ task, increase monitoring item name written
4. Remove the antgroup prefix from the indicator definition name in the integration component
=> feat: support logging integration component

server/all-in-one/all-in-one-bootstrap/pom.xml, server/all-in-one/all-in-one-bootstrap/src/main/java/io/holoinsight/server/allinone/bootstrap/HoloinsightAllInOneBootstrap.java, server/common/common-service/pom.xml, server/extension/extension-common-flyway/pom.xml, server/extension/extension-common-flyway/src/main/java/io/holoinsight/server/common/flyway/FlywayAutoConfiguration.java, server/extension/extension-common-flyway/src/main/java/io/holoinsight/server/common/flyway/FlywayProperties.java, server/extension/extension-common-flyway/src/main/java/io/holoinsight/server/common/flyway/FlywayService.java, server/extension/extension-common-flyway/src/main/java/io/holoinsight/server/common/flyway/FlywaydbController.java, server/extension/extension-common-flyway/src/main/resources/META-INF/spring.factories, server/extension/extension-common-flyway/src/main/resources/db/migration/V1__230301_INIT_DDL.sql, server/extension/extension-common-flyway/src/main/resources/db/migration/V2__230301_Uniform_COLUMN.sql, server/server-parent/pom.xml
Closes #224 
Fix the problem that classpath:/db/migration configuration directory is missing when deploying independently
Add the extension-common-flyway module to manage flyway-related configuration independently, to avoid introducing flyway-core in the common-service
no
Local test.
=> fix: missing db migration

deploy/examples/k8s/overlays/example/init-db.sh
Closes #
Fix k8s demo db init error
fix k8s demo db init error
No
Local test
=> fix: fix k8s demo db init error

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AlertTaskCompute.java
Closes #248 
- Fix potential NPE issue
- Comments in English
None.
Local test.
=> fix(home): fix NPE in alert compute

server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/dto/IntegrationPluginDTO.java, server/home/home-dal/src/test/java/io/holoinsight/server/home/dal/model/dto/IntegrationPluginDTOTest.java
- Add extraMap in DataRange for extra imfomation.
None.
Unit test: `server/home/home-dal/src/test/java/io/holoinsight/server/home/dal/model/dto/IntegrationPluginDTOTest.java`
=> fix(home): add extra map

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/function/FunctionConfigParam.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AbstractUniformInspectRunningRule.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/Current.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/data/load/RuleAlarmLoadData.java, server/home/home-alert/src/test/java/io/holoinsight/server/home/alert/service/calculate/CurrentTest.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/trigger/Trigger.java
Closes #255 
- Configurable zero fill field.
- Replace Chineses comments to English.
- User can specify zero fill policy in alert rule creation.
Unit test: `server/home/home-alert/src/test/java/io/holoinsight/server/home/alert/service/calculate/CurrentTest.java`
=> feat(home): alert zero fill

server/extension/extension-common-flyway/src/main/resources/db/migration/V3__230321_AlarmRule_COLUMN_workspace.sql
Closes #258 
Add `workspace` clolumn in `alarm_rule` table.
None.
E2E.
=> fix(home): fix alarm_rule workspace

scripts/docker/supervisord.conf, test/scenes/scene-default/after.sh, test/scenes/scene-default/log-generator.py, test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/BaseIT.java, test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/LogMonitoring_1_log_IT.java, test/server-e2e-test/src/test/resources/requests/LogMonitoring_1_log_IT.json
Closes #
Add second log monitoring E2E test
Add second log monitoring E2E test
No
Local test
=> test: add second log monitoring E2E test

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlarmHistoryServiceImpl.java
Closes #
Fix the alert history query condition, query alert in process.
User can query alert history which is triggering alert.
Local test.
=> fix(home): fix alert history query condition

.github/workflows/e2e-test.yml, scripts/test/e2e/all.sh, scripts/test/e2e/one.sh, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/data/load/RuleAlarmLoadData.java, test/scenes/common/base.yaml, test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/bootstrap/IntegrationBootstrapHelper.java, test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/bootstrap/OneIntegrationBootstrapIT.java, test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/bootstrap/SceneDefaultIT.java, test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/utils/MemoryTestExecutionListener.java
Closes #
- Print E2E test results after test execution
- `./scripts/test/e2e/all.sh` and `one.sh` scripts will fail if any E2E test fails
No
Local test
=> test: optimize e2e result print

deploy/examples/docker-compose/.env, deploy/examples/docker-compose/ceresdb_entrypoint.sh, deploy/examples/k8s/base/ceresdb.yaml, server/extension/extension-storage-ceresdbx/pom.xml, server/extension/extension-storage-ceresdbx/src/main/java/io/holoinsight/server/extension/ceresdbx/CeresdbxClientManager.java, server/extension/extension-storage-ceresdbx/src/main/java/io/holoinsight/server/extension/ceresdbx/CeresdbxMetricStorage.java, test/scenes/common/base.yaml
Closes #283
Ceresdb:v1.0.0 provides powerful cluster capabilities and higher availability, so we decided to adapt it
- ceresdb image updated to v1.0.0
- ceresdb sdk updated to 1.0.1
When users use the latest code to deploy holoinsight-server, they need to re-deploy ceresdb:v1.0.0+ version synchronously to adapt to this update
Local test
=> feat: update ceresdb sdk

server/common/common/src/main/java/io/holoinsight/server/common/LatchWork.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/model/DelTagReq.java
Closes #
1. add the metricTable key clean function, support batch cleaning
2. add **_LatchWork_** utility class, supprt **_CountDownLatch_**
=> feat: add the metricTable key clean function

server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/CommonBuilder.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/NetworkAddressMappingEsStorage.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/SpanMetricEsStorage.java
Closes #
fix some bugs
- percentile aggregation merged into one
- SpanMetricStorage esClient() take effect
=> fix(apm): fix some bugs

scripts/test/e2e/all.sh, test/scenes/common/setup-env.sh, test/scenes/scene-default/after.sh, test/scenes/scene-default/docker-compose.yaml, test/scenes/scene-default/down.sh, test/scenes/scene-default/mysql-exec.sh, test/scenes/scene-default/server-exec.sh, test/scenes/scene-default/server-replace.sh, test/scenes/scene-default/up.sh, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/env/DockerComposeEnv.java
Closes #
- abort testing if after.sh fails
- add more e2e helper scripts
No
Local test
=> test: optimize e2e

server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/CommonBuilder.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/EndpointEsStorage.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/NetworkAddressMappingEsStorage.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/ServiceInstanceEsStorage.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/ServiceOverviewEsStorage.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/SlowSqlEsStorage.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/SpanEsStorage.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/SpanMetricEsStorage.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/TopologyEsStorage.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/VirtualComponentEsStorage.java, server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/scheduler/CacheUpdateScheduler.java, server/apm/apm-server/apm-service/src/main/java/io/holoinsight/server/apm/server/service/impl/NetworkAddressMappingServiceImpl.java
Closes #
Apm query extract range time field for enterprise to inherit
=> feat(apm): extract range time field

server/apm/apm-common/src/main/java/io/holoinsight/server/apm/common/constants/Const.java, server/apm/apm-common/src/main/java/io/holoinsight/server/apm/common/model/specification/OtlpMappings.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/SpanEsStorage.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/SpanMetricEsStorage.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/postcal/PostCalMetricStorage.java
Closes #
This PR is to fix query problems with tags starting with `resource.`.
Fix the relevant code in OtlpMappings.java, add comments, and rename some functions more reasonably.
None.
=> fix: fix incorrect opentelemetry mapping of resource.*

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AlgorithmHttp.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/ValueDownAbnormalDetect.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/ValueUpAbnormalDetect.java
Closes #305 
- Add TraceID to the log called by the algorithm detection.
- Add statistical logs to record the results of calls and the cost for the calls. 
None.
Local test.
=> feat(home): Add TraceID to the log recorded by the algorithm detection

.github/workflows/e2e-test.yml, server/home/home-web/src/main/java/io/holoinsight/server/home/web/common/ParaCheckUtil.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmGroupFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmRuleFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/SysFacadeImpl.java, server/home/home-web/src/test/java/io/holoinsight/server/home/web/common/ParaCheckUtilTest.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AlertGroupIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AlertRuleIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/bootstrap/ITSets.java
Closes #293 
Alert rule names and notification group names only support uppercase and lowercase letters, numbers, Chinese characters, and `-`, `_`, `,` and `.`.
- Checks whether the contents of the string are valid in `server/home/home-web/src/main/java/io/holoinsight/server/home/web/common/ParaCheckUtil.java` 
- Check alarm group name in `io.holoinsight.server.home.web.controller.AlarmGroupFacadeImpl#save` and `io.holoinsight.server.home.web.controller.AlarmGroupFacadeImpl#update`
- Check alarm rule name in `io.holoinsight.server.home.web.controller.AlarmRuleFacadeImpl#save` and `io.holoinsight.server.home.web.controller.AlarmRuleFacadeImpl#update`
None.
Unit test: `server/home/home-web/src/test/java/io/holoinsight/server/home/web/common/ParaCheckUtilTest.java`
E2E tests: 
- …
=> fix(home): fix security vulnerability

server/extension/extension-storage-ceresdbx/pom.xml, server/extension/extension-storage-ceresdbx/src/main/java/io/holoinsight/server/extension/ceresdbx/CeresdbxMetricStorage.java, server/extension/extension-storage-ceresdbx/src/main/java/io/holoinsight/server/extension/ceresdbx/HoloinsightCeresdbxConfiguration.java, server/extension/extension-storage-remote-promql/pom.xml, server/extension/extension-storage-remote-promql/src/main/java/io/holoinsight/server/extension/promql/HttpPqlQueryService.java, server/extension/extension-storage-remote-promql/src/main/java/io/holoinsight/server/extension/promql/PqlQueryService.java, server/extension/extension-storage-remote-promql/src/main/java/io/holoinsight/server/extension/promql/RemotePqlConfiguration.java, server/extension/extension-storage-remote-promql/src/main/java/io/holoinsight/server/extension/promql/RemotePqlProperties.java, server/extension/extension-storage-remote-promql/src/main/java/io/holoinsight/server/extension/promql/model/Endpoint.java, server/extension/extension-storage-remote-promql/src/main/java/io/holoinsight/server/extension/promql/model/PqlResult.java, server/extension/extension-storage-remote-promql/src/main/java/io/holoinsight/server/extension/promql/utils/HttpClientUtils.java, server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/MetricStorage.java, server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/model/PqlParam.java, server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/model/QueryMetricsParam.java, server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/model/QueryParam.java, server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/model/QueryResult.java, server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/model/WriteMetricsParam.java, server/query/query-service/src/main/java/io/holoinsight/server/query/service/impl/DefaultQueryServiceImpl.java, server/server-parent/pom.xml, test/scenes/common/base.yaml, test/scenes/common/prometheus.yml, test/scenes/scene-default/application.yaml, test/scenes/scene-default/docker-compose.yaml, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/CeresdbPqlMonitoringIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/bootstrap/ITSets.java, test/server-e2e-test/src/main/resources/requests/CeresdbPqlMonitoringIT.json
Closes #309 
Support remote PromQL
For time series databases that do not natively support PromQL but implement Remote Read/Write of promethues, you can use promethues as a proxy to implement PromQL queries
no
local test
=> feat: support remote PromQL

test/scenes/common/up.sh
Closes #312 
1. use `$project_root` instead of `$project` in `up.sh`
No
Local test
=> fix: fix up.sh

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AlertTaskCompute.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AlgorithmHttp.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/data/load/AIAlarmLoadData.java
Closes #319 
Classify the alarm content and adjust some of the alarm content to the debug level.
None.
Local test.
=> feat(home): improve alert log level

server/home/home-common/src/main/java/io/holoinsight/server/home/common/util/scope/MonitorCookieUtil.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/InitFacadeImpl.java
Closes #
1. add workspace in cookies where workspace/tenant switch, and the params of workspace is not required
=> feat: support add workspace cookies when tenant/workspace switch

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictKey.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictUtil.java
Closes #
enable a metering_log trigger by meta dict
=> feat: add metering trigger

server/extension/extension-storage-ceresdbx/pom.xml
Closes #324 
update ceresdb SDK to 1.0.3
=> fix: garbled characters

server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/DefaultTenantFacadeImpl.java
Closes #331 
1. add webapi _**/webapi/tenant/config/{name}**_
=> fix(home): add webapi /webapi/tenant/config/{name}

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertNotifyHandler.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/GatewayService.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/GetSubscriptionHandler.java
Closes #
Add some logs for troubleshooting.
None.
None.
=> feat(home): add logs for troubleshooting

.github/workflows/e2e-test.yml, server/extension/extension-storage-ceresdbx/src/main/java/io/holoinsight/server/extension/ceresdbx/CeresdbxMetricStorage.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/MetricMonitoringIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/bootstrap/ITSets.java
Closes #118 
no
Verified by e2e test, see MetricMonitoringIT for details
=> fix: the value of tags is empty

test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/LogMonitoringIT.java
=> fix: fix it

server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/MetricMonitoringIT.java
=> test: fix it

test/scenes/common/base.yaml, test/scenes/common/grafana/grafana.ini, test/scenes/common/status.sh, test/scenes/scene-default/docker-compose.yaml
=> test: add grafana container

test/scenes/common/base.yaml, test/scenes/scene-default/docker-compose.yaml
=> test: optimize test scripts

server/common/common/src/main/java/io/holoinsight/server/common/RetryUtils.java
Closes #
`previewFile` webapi is slow, cost > 1000ms.
- sleep only when retry
=> refactor: sleep only when retry

server/meta/meta-common/src/main/java/io/holoinsight/server/meta/common/util/ConstModel.java, server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/service/MongoDataCoreService.java
Closes #
1. sovle problem of meta fuzzyByExample, only ip/hostname fuzzy matching is supported, everything else is exact matching
=> fix: sovle problem of meta fuzzyByExample

server/extension/extension-storage-ceresdbx/src/main/java/io/holoinsight/server/extension/ceresdbx/CeresdbxMetricStorage.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/MetricMonitoringIT.java
Closes #
fix metric is not exist
=> fix: metric is not exist

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/TenantInitService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/DefaultTenantInitServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/TraceQueryFacadeImpl.java
Closes #
1. update the webapi route of the trace facade
before:
> '/webapi/v1/query/service/query/serviceList',
>   '/webapi/v1/query/trace/query/basic',
>   '/webapi/v1/query/topology/query/topology',
>   '/webapi/v1/query/serviceInstance/query/serviceInstanceList',
>   '/webapi/v1/query/endpoint/query/endpointList',
>   '/webapi/v1/query/component/query/componentList',
updated:
> '/webapi/v1/trace/query/basic',
>   '/webapi/v1/trace/query/span',
>   '/webapi/v1/trace/query/serviceList',
>   '/webapi/v1/trace/query/endpointList',
>   '/webapi/v1/trace/query/serviceInstanceList',
>   '/webapi/v1/trace/query/componentList',
>   '/webapi/v1/trace/query/componentTraceIds',
>   '/webapi/v1/trace/query/topology'
_
=> feat: update the webapi route of the trace facade

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/log/Log.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/log/LogContextRequest.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/log/LogContextResponse.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/log/LogCountRequest.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/log/LogCountResponse.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/log/LogKey.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/log/LogMultiQueryRequest.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/log/LogMultiQueryResponse.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/log/LogPathRequest.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/log/LogQueryRequest.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/log/LogQueryResponse.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/log/LogService.java
=> feat: add log query interface (#362)

.github/workflows/e2e-test.yml, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/apm/ApmAppMetricStatIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/apm/ApmCallLinkDetailIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/apm/ApmCallLinkIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/apm/ApmTopologyIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/bootstrap/ITSets.java
Closes #
- Add APM E2E tests
1. Test topology
2. Test trace search
3. Test APM metrics
=> test: add APM ITs

test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/LogMonitoringIT.java
Closes #
LogMonitoringIT occasionally fails because it relies on a second-level updated log.  
This can easily happen during the first few minutes of program startup.  
I modified the assertion method to make it more stable.
=> test: make LogMonitoringIT more stable

server/registry/registry-model/src/main/java/io/holoinsight/server/registry/model/GroupBy.java
Closes #
See #379 
Add log analysis models
No
=> feat: add log analysis models

test/scenes/common/status.sh, test/scenes/common/utils/prettytable/LICENSE, test/scenes/common/utils/prettytable/prettytable.sh
Closes #
Print better message in shell
```text
$./status.sh
...
Name                              Command                  State                                                    Ports
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
...
scene-default_server_1          /entrypoint.sh                   Up (healthy)   0.0.0.0:10765->7681/tcp, 0.0.0.0:10766->80/tcp, 0.0.0.0:10764->8000/tcp, 0.0.0.0:10763->8080/tcp
...
┌───────────────────────┬──────────────────────────────────────────────┐
│  Component            │  Access                                      │
├───────────────────────┼──────────────────────────────────────────────┤
│  Server_UI            │ …
```
=> test: print better message in shell

test/scenes/common/base.yaml, test/scenes/scene-default/up.sh, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/env/DockerComposeEnv.java
Closes #
It is useful to automatically enable debug mode when developing.
When debug mode is enabled:
- Java remote debugger is enabled
- Start MySQL/MongoDB/ES WebUI (myphpadmin/mongo-express/kibana/grafana)
No
Local test
=> test: automatically enable debug mode when developing

.github/workflows/e2e-test.yml, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/TaskScheduleFacadeImpl.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/TaskIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/bootstrap/ITSets.java
Closes #
Fix `TaskIT` test.
- Add default list in `server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/TaskScheduleFacadeImpl.java`
None.
E2E test: `server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/TaskScheduleFacadeImpl.java`
=> fix(home): fix TaskIT e2e

server/query/query-service/src/main/java/io/holoinsight/server/query/service/impl/DefaultQueryServiceImpl.java
Closes #
Fix the incorrect aggregator of error analysis.
the incorrect aggregator of error analysis.
None.
=> fix: fix analysis

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertSaveHistoryHandler.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/model/HostingAlert.java
Closes #
Add `workspace` to `AlarmHistoryDetail` and `HostingAlert`
- Add `workspace` to `AlarmHistoryDetail` in `server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertSaveHistoryHandler.java`
- Add `workspace` to `HostingAlert` in `server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/model/HostingAlert.java`
None.
E2E.
=> fix(home): add workspace content

server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/service/MongoDataCoreService.java
Closes #
1. update mongo insertorupdate
=> feat(meta): update mongo insertorupdate

deploy/examples/k8s/base/cadvisor.yaml, deploy/examples/k8s/base/ceresdb.yaml, deploy/examples/k8s/base/clusteragent.yaml, deploy/examples/k8s/base/kustomization.yaml, deploy/examples/k8s/base/prometheus.yaml, deploy/examples/k8s/base/server.yaml, deploy/examples/k8s/overlays/example/delete.sh, deploy/examples/k8s/overlays/example/init-db.sh, deploy/examples/k8s/overlays/example/mysql-exec.sh
Closes #
Fix the startup problem of k8s demo.
- Fix startup problem of ceresdb
- `clusteragent` starts after holoinsight-server
- Add prometheus container
- Use same sql as `scene-default`
=> fix: fix k8s demo

server/all-in-one/all-in-one-bootstrap/src/main/resources/config/application.yaml, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/compute/algorithm/anomaly/AlgorithmConfig.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/compute/algorithm/anomaly/AnomalyAlgorithmRequest.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/compute/algorithm/anomaly/AnomalyAlgorithmResponse.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/compute/algorithm/anomaly/RuleConfig.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AnomalyDownAbnormalDetect.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AnomalyUpAbnormalDetect.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/FunctionManager.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/ValueDownAbnormalDetect.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/ValueUpAbnormalDetect.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/data/load/AIAlarmLoadData.java, server/home/home-bootstrap/src/test/resources/config/application-test.yaml, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/emuns/FunctionEnum.java, test/scenes/scene-default/docker-compose.yaml
Closes #404 
add intelligent anomaly detection capability to the alarm
Add the algorithm interface model in
/holoinsight/server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/compute/algorithm/anomaly
Added abnormal down trigger in
/holoinsight/server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AnomalyDownAbnormalDetect.java
Added abnormal up trigger in
/holoinsight/server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AnomalyUpAbnormalDetect.java
none
none
=> refactor: add intelligent anomaly detection capability to the alarm

server/query/query-service/src/main/java/io/holoinsight/server/query/service/impl/DefaultQueryServiceImpl.java
Closes #
Merge the aggregated `analysis` data points into one `Result`.
Merge the aggregated `analysis` data points into one `Result`.
None.
=> fix: fix analysis points

server/extension/extension-storage-ceresdbx/src/main/java/io/holoinsight/server/extension/ceresdbx/CeresdbxMetricStorage.java
Closes #
There is special metric whose value is a string. Currently, the code does not handle such cases.
- Check string value when insert and query
=> fix: fix ceresdb string field

.github/workflows/e2e-test.yml, test/scenes/common/log-alert-generator.py, test/scenes/common/log-generator.py, test/scenes/common/logwriter.py, test/scenes/scene-default/docker-compose.yaml, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/LogMonitoringAnalysisIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/bootstrap/ITSets.java, test/server-e2e-test/src/main/resources/requests/AlertCalculateIT.json, test/server-e2e-test/src/main/resources/requests/LogMonitoringAnalysisIT.json
Also see #379 
1. add loganalysis IT
=> test: add loganalysis IT

.github/workflows/e2e-test.yml, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertSaveHistoryHandler.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlarmHistoryDetailServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/common/ParaCheckUtil.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AlertCalculateIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AlertLogAnalysisIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/bootstrap/ITSets.java, test/server-e2e-test/src/main/resources/requests/LogAnalysisIT.json
Closes #
Add e2e test case, for #412 
- `test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AlertLogAnalysisIT.java`
None.
- `test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AlertLogAnalysisIT.java`
=> test: add e2e of log analysis IT

test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AlertLogAnalysisIT.java
Closes #
temporary rm AlertLogAnalysisIT
temporary rm AlertLogAnalysisIT
=> test: temporary rm AlertLogAnalysisIT

test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AlertLogAnalysisIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/bootstrap/ITSets.java
Closes #
fix  rm AlertLogAnalysisIT
rm AlertLogAnalysisIT
=> fix: rm AlertLogAnalysisIT

server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/collecttarget/CollectTargetMaintainer.java, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/collecttarget/CollectTargetService.java, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/collecttarget/TargetHostIPResolver.java
Closes #
support custom hostIP resolution
1. Add TargetHostIPResolver interface
2. Call TargetHostIPResolver when build refAgent
=> refactor: support custom hostIP resolution

.dockerignore, scripts/docker/Dockerfile, scripts/docker/build.sh, scripts/front/Dockerfile, scripts/front/build-image.sh, scripts/front/build.sh
Closes #
Add front scripts
Add front scripts for:
1. build front code
2. build front docker image
=> refactor: add front scripts

server/common/common/src/main/java/io/holoinsight/server/common/SSRFHook.java, server/common/common/src/main/java/io/holoinsight/server/common/SSRFUtils.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/dto/conf/CollectMetric.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/dto/conf/LogKnownPattern.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/dto/conf/LogParse.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/GaeaSqlTaskUtil.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictType.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/PortCheckPlugin.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/IntegrationProductService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/IntegrationProductServiceImpl.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/AbstractMetricCrawlerBuilder.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/MetricCrawler.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/MetricCrawlerBuilder.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/MetricCrawlerConstant.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/TaskFactoryHolder.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/TenantMetricCrawlerTask.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/crawler/ApmMetricCrawlerBuilder.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/crawler/JvmMetricCrawlerBuilder.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/crawler/PortCheckMetricCrawlerBuilder.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/crawler/SystemMetricCrawlerBuilder.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/crawler/TenantMetricCrawlerTaskJob.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/crawler/TenantMetricCrawlerTaskJobArgs.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/common/MonitorBeanPostProcessor.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmWebhookFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/MetricInfoFacadeImpl.java, server/query/query-server/src/main/java/io/holoinsight/server/query/server/controllers/QueryController.java, server/registry/registry-model/src/main/java/io/holoinsight/server/registry/model/integration/IntegrationTask.java, server/registry/registry-model/src/main/java/io/holoinsight/server/registry/model/integration/IntegrationTransForm.java
Closes #
1.  move SSRFHook to common-module
2.  Change the prefix of the indicator name in PortCheckPlugin
3. add metric_prefix in integrationtask
4. add metricCrawlerTask
=> feat(home): add metricCrawlerTask

server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/EndpointEsStorage.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/ServiceInstanceEsStorage.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/ServiceOverviewEsStorage.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/TopologyEsStorage.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/VirtualComponentEsStorage.java
Closes #
Optimize apm part of the query
=> fix: fix apm query

server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/dto/IntegrationMetricDTO.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/crawler/SystemMetricCrawlerBuilder.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/IntegrationProductFacadeImpl.java
Closes #
1. optimize the crawlerTask
2. replace the metrics in **_integration_product_** with the information in the **_metric_info_** table
=> feat: Optimize the crawlerTask

server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/builder/RPCTrafficSourceBuilder.java
=> fix: fix build trace relation

server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/analysis/RelationAnalysis.java
Closes #
Fix the null judgment logic of net.peer.name when analysis client span
=> fix: fix analysis client span

server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/RegistryService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/config/PortCheckPluginConfig.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/PortCheckPlugin.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/agent/AgentLogTailService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/CustomPluginServiceImpl.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/crawler/ApmMetricCrawlerBuilder.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AgentFacadeImpl.java, server/registry/registry-model/src/main/java/io/holoinsight/server/registry/model/integration/portcheck/PortCheckTask.java
Closes #
1. add _**MonitorException**_ in _**AgentFacadeImpl**_，and return **_hostname_** in response
2. add _**ports**_ params in **_PortCheckTask_**
=> feat(home): optimize integration component functions

server/common/common/src/main/java/io/holoinsight/server/common/JsonResult.java, server/common/common/src/main/java/io/holoinsight/server/common/RetryUtils.java, server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/RegistryService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/agent/AgentLogTailService.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AgentFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmWebhookFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/BaseFacade.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/OpenmetricsScraperFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/TraceQueryFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/UserFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/interceptor/MonitorScopeAuthInterceptor.java, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/grpc/BiStreamService.java, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/grpc/RegistryServiceForProdImpl.java, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/grpc/stream/ServerStreamImpl.java, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/grpc/stream/ServerStreamManager.java
Closes #
- Rename 'createFailResult' to 'fillFailResultTo'
- Remove retry of calling regsitry grpc
- Handle bistream error
=> refactor: error handle

server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/RegistryService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/agent/AgentLogTailService.java
Closes #
- Add charset to response
=> refactor: add charset to resp

deploy/examples/docker-compose/application.yaml, server/extension/extension-storage-ceresdbx/src/main/java/io/holoinsight/server/extension/ceresdbx/HoloinsightCeresdbxConfiguration.java
Closes #443 
- Supplement missing configuration items
- Set pqlQueryService as a non-required dependency
=> fix: Holoinsight demo startup failure

server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/ServiceOverviewEsStorage.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/SlowSqlEsStorage.java
=> fix(apm): fix query apm service list

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/TenantInitService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/DefaultTenantInitServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/filter/Step2IdentityFilter.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/filter/Step3AuthFilter.java
Closes #
1. optimize auth filter, return 403 
2. optimize the result of  check login filter
3. optimize the trace tenant
=> feat(home): optimize auth filter

server/home/home-common/src/main/java/io/holoinsight/server/home/common/util/scope/MonitorUser.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/SearchFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/filter/Step3AuthFilter.java
Closes #
1. Optimize the return errorcode of the **_Step3AuthFilter_**, return **_SC_FORBIDDEN_** 403
=> feat(home): optimize return errorcode of the authfilter

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictKey.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictType.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/TenantInitService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlertDingDingRobotServiceImpl.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlertGroupServiceImpl.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlertRuleServiceImpl.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlertWebhookServiceImpl.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/DashboardServiceImpl.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/DefaultTenantInitServiceImpl.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/OpenmetricsScraperServiceImpl.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/TenantIntegrationGeneratedTask.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/UserFavoriteFacadeImpl.java
Closes #
1. optimize the result of alarm controller, return **_creator_** and **_modifier_**
=> feat: optimize the result of alarmFacadeImpl

server/meta/meta-dal/src/main/java/io/holoinsight/server/meta/dal/service/mapper/MetaDataMapper.java, server/meta/meta-dal/src/main/resources/sqlmap/MetaDataMapper.xml
=> fix: sqlInjection

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/event/AlertNotify.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/GetSubscriptionHandler.java, server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/QueryClientService.java
=> fix: ineffective global webhook

server/home/home-common/src/main/java/io/holoinsight/server/home/common/util/scope/MonitorCookieUtil.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/UserFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/filter/Step3AuthFilter.java
Closes #
1. optimize set cookies of filters
=> refactor(home): optimize set cookies of filters

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/agent/AgentLogTailService.java
Closes #
1. solve tenant problem of agent logtail
=> fix: sovle problem of agent logtail

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/NullValueTracker.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/data/load/RuleAlarmLoadData.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmRuleFacadeImpl.java
If the creater and modifier has been specified by frontend, then use it.
The creater and modifier will be specified by frontend.
=> fix: alarm rule creater and modifier

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/ula/MonitorULA.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/ula/ULA.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/ula/ULAFacade.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/filter/Step3AuthFilter.java
=> refactor: optimize ULA

server/apm/apm-boot/src/main/java/io/holoinsight/server/apm/bootstrap/HoloinsightApmConfiguration.java, server/apm/apm-server/apm-service/src/main/java/io/holoinsight/server/apm/server/service/impl/ApmMetricMaterializer.java
Closes #
This PR is to make some minor optimizations to the APM module.
1. Replace `MetricStorage` with `MetricService` to log the service time in `ApmMetricMaterializer.java`;
2. The `SpanHandler` Bean will be registered late to ensure that APM-related initialization work has been completed.
None.
=> feat: optimize APM

server/meta/meta-common/src/main/java/io/holoinsight/server/meta/common/util/ConstModel.java, server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/MetaServiceConfiguration.java, server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/service/grpc/DataServiceGrpcImpl.java, server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/web/controller/AdminController.java
=> fix: meta mysql write

server/all-in-one/all-in-one-bootstrap/src/main/resources/config/application.yaml, server/extension/extension-common-flyway/src/main/resources/db/migration/V1__230301_INIT_DDL.sql, server/extension/extension-common-flyway/src/main/resources/db/migration/V8__230607_CHANGE_integration_plugin_COLUMN.sql, server/meta/meta-common/src/main/java/io/holoinsight/server/meta/common/model/QueryExample.java, server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/service/AbstractDataCoreService.java, server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/service/MongoDataCoreService.java, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/meta/MetaSyncService.java
Closes #469 
1. optimize the metadata sync task reported by holoinsight-agent
2. the **_workspace_** in the **_integration_plugin_** table is set to default null
=> refactor: optimize the metadata sync reported by agent

server/extension/extension-common-flyway/src/main/resources/db/migration/V9__230609_CREATE_userinfo_TABLE.sql, server/home/home-boot/src/main/java/io/holoinsight/server/home/bootstrap/HoloinsightHomeConfiguration.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/converter/UserinfoConverter.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/mapper/UserinfoMapper.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/mapper/UserinfoVerificationMapper.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/Userinfo.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/UserinfoVerification.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/UserinfoDTO.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/UserinfoVerificationService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/UserinfoVerificationServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/common/ParaCheckUtil.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/UserinfoFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/UserinfoVerificationFacadeImpl.java
Closes #481 
Maintaining user information and support  identity verification.
- Add `userinfo` and `userinfo_verification`
- Check verification code for identity verification.
-  CRED for user information.
=> feat: user information

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictKey.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictUtil.java
Closes #
add meter submit trigger.
=> feat: add meter submit trigger

server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/service/SqlDataCoreService.java
=> feat: meta add log

server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/dto/CustomPluginDTO.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlarmHistoryDTO.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/listener/CustomPluginUpdateListener.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/listener/IntegrationPluginUpdateListener.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/listener/OpenmetricsScraperUpdateListener.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/IntegrationProductService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/IntegrationProductServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmHistoryFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmRuleFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/CustomPluginFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/MetricInfoFacadeImpl.java
Closes #
1.  add relationship between logmonitor and alarmrule
=> refactor: add relationship between logmonitor and alarmrule

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/TenantInitService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/DefaultTenantInitServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/InitFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java
Closes #
1. Fixed horizontal security vulnerabilities
=> fix: horizontal security vulnerabilities

server/home/home-common/src/main/java/io/holoinsight/server/home/common/util/scope/AuthTargetType.java, server/home/home-common/src/main/java/io/holoinsight/server/home/common/util/scope/MonitorAuth.java, server/home/home-common/src/main/java/io/holoinsight/server/home/common/util/scope/MonitorCookieUtil.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/ula/MonitorULA.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/ula/ULA.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/ula/ULAFacade.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/filter/Step3AuthFilter.java
Closes #
1. solve the problem of horizontal overreach in filters
=> refactor: solve the problem of horizontal overreach

server/common/common-service/src/main/java/io/holoinsight/server/common/service/MetricInfoServiceImpl.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/trigger/DataSource.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/UserOpLogServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/MetricInfoFacadeImpl.java
Closes #
1. add metric info in **_AlarmRule_**
=> refactor: add metric info in alarmrule

server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/service/SqlDataCoreService.java
Closes #500
Ensure that metadata information is consistent across multiple servers as much as possible
=> feat: update meta sync

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/CacheAlertTask.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlarmHistoryDetailServiceImpl.java
Closes #503 
Fix alert bug.
- When pageSize = 0, skip to get alert task.
None.
=> fix: alert coordinator

server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmHistoryDetailFacadeImpl.java
Closes #
`/countTrend` Sort in ascending order instead of descending order according to alarmTime.
None.
=> fix: select alert detail sort

server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/SpanEsStorage.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/storage/SpanStorage.java, server/apm/apm-server/apm-service/src/main/java/io/holoinsight/server/apm/server/service/TraceService.java, server/apm/apm-server/apm-service/src/main/java/io/holoinsight/server/apm/server/service/impl/TraceServiceImpl.java, server/apm/apm-server/apm-web/src/main/java/io/holoinsight/server/apm/web/impl/TraceApiController.java, server/query/query-service/src/main/java/io/holoinsight/server/query/service/impl/DefaultQueryServiceImpl.java
Closes #
Query trace interface supports tags as query conditions
=> feat: query trace with tags

server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/trigger/DataSource.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/DashboardService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/DashboardServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/common/ParaCheckUtil.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/UserFavoriteFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/filter/Step3AuthFilter.java
Closes #
1. Resolve horizontal overreach
=> refactor: optimize horizonal overreach

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/AlertTaskScheduler.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/TimeFilter.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmHistoryDetailFacadeImpl.java
Closes #513 
Fix time filter.
None.
=> fix: alert time filter

server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/ServiceInstanceEsStorage.java
Closes #
Fix query apm service instance list with term params
=> fix: fix query apm service instance list

server/home/home-common/src/main/java/io/holoinsight/server/home/common/util/cache/local/CommonLocalCache.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/ula/UserCache.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/TenantIntegrationGeneratedTask.java, server/query/query-service/src/main/java/io/holoinsight/server/query/service/analysis/AggCenter.java
Closes #
1. sovle problem of integrationGeneratedTask when sync appMeta;
=> fix(home): integrationGeneratedTask

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/listener/CustomPluginUpdateListener.java
Closes #520 
holoinsight need to support internationalization
Change some Chinese comments to English
Need to understand English
Check the notes for your own changes
=> docs: change chinese notes to english notes

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/ula/MonitorULA.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/TenantIntegrationGeneratedTask.java
Closes #
1. integrationGeneratedTask update, add **_logPattern_** in app generated task
=> refactor: integrationGeneratedTask update

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/CacheAlertTask.java
Closes #524 
Fix the issue of alert configuration loading potentially crashing
None.
=> fix: alert cache exception

server/common/common-service/src/main/java/io/holoinsight/server/common/config/EnvironmentProperties.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/common/webhook/WebhookUtil.java
Closes #
Add location for difference deployment zone.
None
=> chore: add location property

server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/service/SqlDataCoreService.java
=> feat: add log for data clean task

scripts/docker/Dockerfile
Closes #
Currently, when we build a server-side image, we refer to the front-end build structure through the image.  
Update front docker image.
=> chore: update front docker image

.github/workflows/e2e-test.yml, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/dto/conf/CollectMetric.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/GaeaSqlTaskUtil.java, test/server-e2e-test/pom.xml, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AlarmBlockFacadeIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AlarmMetricFacadeIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AlarmSubscribeFacadeIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AlertManagerWebhookIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AlertTemplateFacadeIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/ApiKeyFacadeIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/CustomPluginFacadeIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/DefaultTenantFacadeIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/DisplayMenuFacadeIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/DisplayTemplateFacadeIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/FolderFacadeIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/InitFacadeIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/IntegrationGeneratedFacadeIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/IntegrationPluginFacadeIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/IntegrationProductFacadeIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/UserFavoriteFacadeIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/UserinfoVerificationFacadeIT.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/bootstrap/ITSets.java
Closes #
1. log sample update
2. add IT test case
=> refactor(home): log sample update

server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/NotificationTemplate.java
Closes #
Add log sample in dingtalk notification template
Get log sampling result in dingtalk alert notification.
=> feat(home): add log content in dingtalk alert template

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/log/LogContextRequest.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/log/LogCountRequest.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/log/LogQueryRequest.java
Closes #
add log type for distinguish different log types
add log type for count, query ,context request
=> feat(home): add type tag for distinguish different log type

server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/TopologyEsStorage.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/storage/TopologyStorage.java, server/apm/apm-server/apm-service/src/main/java/io/holoinsight/server/apm/server/service/impl/TopologyServiceImpl.java
Closes #
It takes too long to query the tenant topology map, modify it to query the upstream and downstream relationships of a single service to build a service topology
=> feat(apm): optimize apm service topology

server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/ServiceErrorEsStorage.java
=> fix: fix query service error

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/data/load/RuleAlarmLoadData.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/NotificationTemplate.java
Closes #544 
Set "1m-none" to downsample for non-aggregate mode.
Fix non-aggregate mode alert calculation.
=> fix: alert calculation fails in non-aggregate mode

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/AlertService.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/event/alertManagerEvent/AlertManagerBuildMsgHandler.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlertTemplateField.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/NotificationTemplate.java
Closes #546 
- Add `checkNotNullValue` in `server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/event/alertManagerEvent/AlertManagerBuildMsgHandler.java`
None
=> feat: check empty field in webhook request of alert notification 

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/data/load/RuleAlarmLoadData.java
Closes #
Set slidingWindow null for none aggregate
=> fix: set slidingWindow null for none aggregate

server/query/query-service/src/main/java/io/holoinsight/server/query/service/impl/DefaultQueryServiceImpl.java
Closes #
query trace with duration.
query trace with duration.
None.
=> fix: fix query trace with duration

server/common/common-service/pom.xml, server/common/common-service/src/main/java/io/holoinsight/server/common/service/MetricInfoService.java, server/common/common-service/src/main/java/io/holoinsight/server/common/service/MetricInfoServiceImpl.java, server/common/common-service/src/main/java/io/holoinsight/server/common/service/SuperCache.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/UserinfoService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/UserinfoServiceImpl.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/ula/ULAFacade.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/UserinfoFacadeImpl.java
Closes #
1. spm update of log monitoring
=> refactor(home): spm update of log monitoring

server/common/common-service/src/main/java/io/holoinsight/server/common/service/MetricInfoServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/CustomPluginFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java, server/query/query-service/src/main/java/io/holoinsight/server/query/service/impl/DefaultQueryServiceImpl.java
Closes #
This PR supports the definition and query of virtual metrics to realize complex calculations such as service success rate.
- A logical branch for handling virtual metrics has been introduced in `DefaultQueryService`.
None.
=> feat: virtual metric

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/GaeaSqlTaskUtil.java
Closes #
1. add translate in afterfilters of log monitoring
=> refactor(home): add translate in afterfilters of log monitoring

server/common/common-service/src/main/java/io/holoinsight/server/common/service/MetricInfoServiceImpl.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/listener/CustomPluginUpdateListener.java
Closes #
1. fix:  spm metric of log monitoring
=> fix(home): spm metric of log monitoring

server/common/common-dao/src/main/java/io/holoinsight/server/common/dao/entity/MetricInfo.java, server/common/common-dao/src/main/java/io/holoinsight/server/common/dao/entity/dto/MetricInfoDTO.java, server/extension/extension-common-flyway/src/main/resources/db/migration/V12__230713_ADD_metricinfo_COLUMN.sql, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/listener/CustomPluginUpdateListener.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/AlarmMetricService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlarmMetricServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmMetricFacadeImpl.java
Closes #
1. add relate of alarmrule and logmonitor
2. add column "ref, ext_info" in **metric_info**
=> refactor(home): add relate of alarmrule and logmonitor

server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/collecttarget/CollectTargetService.java, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/collecttarget/TargetHostIPResolver.java
Closes #
`TargetHostIPResolver` can now returns agentId or hostIP.
=> refactor: refactor hostIP resolver

server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/grpc/RegistryServiceForAgentImpl.java
Closes #
fix metadata deletion logic
=> fix: fix metadata deletion logic

server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/installer/ColumnTypeEsMapping.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/utils/ApmGsonUtils.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/model/EndpointRelationDO.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/model/NetworkAddressMappingDO.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/model/RecordDO.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/model/ServiceInstanceRelationDO.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/model/ServiceRelationDO.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/model/SlowSqlDO.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/model/SpanDO.java, server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/analysis/ServiceErrorAnalysis.java, server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/analysis/SlowSqlAnalysis.java
Closes #
This PR is to cooperate with the compatible transformation of the APM timing field change.
1. Add a @timestamp field for APM entities.
None.
=> feat: add @timestamp as a apm timeseries field

server/extension/extension-common-flyway/src/main/resources/db/migration/V13__230718_ADD_workspace_COLUMN.sql, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/AlarmDingDingRobot.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/AlarmGroup.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/dto/AlarmDingDingRobotDTO.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/dto/AlarmGroupDTO.java
Closes #
Add `workspace` for `AlarmDingDingRobot` and `AlarmGroup`
None.
=> fix: add workspace field

server/common/common-service/src/main/java/io/holoinsight/server/common/service/MetricInfoService.java, server/common/common-service/src/main/java/io/holoinsight/server/common/service/MetricInfoServiceImpl.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/DefaultTenantInitServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/SearchFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/model/TagQueryRequest.java
Closes #
1.  add conditons when query tagvalues
=> refactor(home): add conditons when query tagvalues

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlertRuleServiceImpl.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/CustomPluginServiceImpl.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/DashboardServiceImpl.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/FolderServiceImpl.java
Closes #
1. solve problem of queryByKeyword
=> fix(home): solve problem of queryByKeyword

server/common/common-service/src/main/java/io/holoinsight/server/common/service/MetricInfoServiceImpl.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/AbstractMetricCrawlerBuilder.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/crawler/TenantMetricCrawlerTaskJob.java
Closes #
1. add log in metricCrawler
=> refactor(home): add log in metricCrawler

server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/installer/ColumnTypeEsMapping.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/utils/ApmGsonUtils.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/model/EndpointRelationDO.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/model/NetworkAddressMappingDO.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/model/RecordDO.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/model/ServiceInstanceRelationDO.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/model/ServiceRelationDO.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/model/SlowSqlDO.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/model/SpanDO.java, server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/analysis/ServiceErrorAnalysis.java, server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/analysis/SlowSqlAnalysis.java
Closes #
This PR is to officially switch the timing field of APM to `@timestamp`.
- The timing field of APM is changed to `@timestamp`.
None.
=> feat: change apm ts field to @timestamp

server/apm/apm-common/src/main/java/io/holoinsight/server/apm/common/constants/Const.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/SpanEsStorage.java, server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/analysis/RelationAnalysis.java, server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/builder/RPCTrafficSourceBuilder.java
Closes #
The missing span needs to fill in the start and end time, and the front-end drawing time axis depends on the time field
=> fix(apm): fix query trace tree

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/IntegrationProductService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/IntegrationProductServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/UserFavoriteFacadeImpl.java, server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/service/SqlDataCoreService.java
Closes #
1. Resolve the horizontal override vulnerability of the userfavorites interface
=> fix(home): resolve the horizontal override vulnerablity

server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/installer/EsModelInstaller.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/installer/IndexStructures.java
Closes #
This PR is to judge whether the settings have changed when installing the APM model, so as to update the index template.
1. Check whether the settings have changed when initializing the model.
2. Set Elasticsearch to asynchronous fsync.
None.
=> feat: apm model settings

server/home/home-common/src/main/java/io/holoinsight/server/home/common/util/cache/local/CacheConst.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/listener/IntegrationGeneratedUpdateListener.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/PortCheckPlugin.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/TenantInitService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/agent/AgentLogTailService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/DefaultTenantInitServiceImpl.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/IntegrationPluginServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/MetaFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/SearchFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/UserFavoriteFacadeImpl.java
Closes #
1. optimzie the **### tenantInitService**
=> refactor(home): optimize tenantInitService

server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/dto/OpenmetricsScraperDTO.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/listener/OpenmetricsScraperUpdateListener.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/OpenmetricsScraperServiceImpl.java, server/registry/registry-model/src/main/java/io/holoinsight/server/registry/model/OpenmetricsScraperTask.java
Closes #
- openmetrics supports relabelconfigs
=> refactor: openmetrics supports relabelconfigs

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/listener/OpenmetricsScraperUpdateListener.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/OpenmetricsScraperFacadeImpl.java
=> fix: setMetricRelabelConfigs

server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/builder/RPCTrafficSourceBuilder.java, server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/trace/SpanHandler.java
=> fix: fix apm log level

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictKey.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/AesUtil.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/config/TraceAuthEncryptConfiguration.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AgentFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/TraceAgentFacadeImpl.java
Closes #
This modification is to make some extensions to the trace access wizard interface
- Extend apikey to support adding custom tags to span
- Support apikey to encrypt symmetrically with AES
```
trace-auth-encrypt:
enable: true
secretKey: xx
iv: xx
```
=> feat: trace guide

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/GatewayService.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/crawler/PgMetricCrawlerBuilder.java
=> fix: alert extra npe

server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/HoloinsightEsConfiguration.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/installer/EsModelInstaller.java
Closes #
```
holoinsight:
storage:
elasticsearch:
shards: 5
replicas: 1
```
=> feat: es shards and replicas extracted into configuration

server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/grpc/RegistryServiceForAgentImpl.java
=> fix: collect target type

server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/dto/IntegrationFormDTO.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/GaeaConvertUtil.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/config/CollectType.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/config/MysqlConfig.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/config/TelegrafConfig.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/AbstractCentralIntegrationPlugin.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/AbstractIntegrationPlugin.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/AbstractLocalIntegrationPlugin.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/MysqlPluginV2.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/MetaService.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/IntegrationProductFacadeImpl.java, server/registry/registry-model/src/main/java/io/holoinsight/server/registry/model/integration/IntegrationTransForm.java, server/registry/registry-model/src/main/java/io/holoinsight/server/registry/model/integration/mysql/MysqlTaskV2.java
Closes #
1. support mysql integration conponent
=> feat(home): support mysql integration conponent

server/common/common-service/src/main/java/io/holoinsight/server/common/model/DataQueryRequest.java, server/common/common-service/src/main/java/io/holoinsight/server/common/service/SuperCache.java, server/common/common-service/src/main/java/io/holoinsight/server/common/service/SuperCacheService.java, server/extension/extension-storage-ceresdbx/src/main/java/io/holoinsight/server/extension/ceresdbx/CeresdbxMetricStorage.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java, server/home/home-web/src/test/java/io/holoinsight/server/home/web/controller/QueryFacadeImplTest.java
Closes #
Make the QueryFacadeImpl interface compatible with SQL query mode.
- Build sql from query request in `server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java`
None.
- `server/home/home-web/src/test/java/io/holoinsight/server/home/web/controller/QueryFacadeImplTest.java`
=> feat: ql query

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertSaveHistoryHandler.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/data/load/RuleAlarmLoadData.java
Closes #
Add filters in query log sample.
=> fix: log sample query

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/listener/IntegrationGeneratedUpdateListener.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/IntegrationGeneratedService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/TenantInitService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/DefaultTenantInitServiceImpl.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/IntegrationGeneratedServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/IntegrationGeneratedFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/IntegrationProductFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java
Closes #
1. optimize integrationGeneratedFacadeImpl
=> refactor(home): optimize integrationGeneratedFacadeImpl

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/log/LogQueryRequest.java
Closes #
1. update params of **_LogQueryRequest_**
=> fix: update params of LogQueryRequest

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/log/Log.java
Closes #
1. optimize logfacadeImpl
=> refactor(home): optimize logfacadeImpl

server/common/common-dao-gen/src/main/java/io/holoinsight/server/common/dao/entity/TraceAgentConfigurationDO.java, server/common/common-dao-gen/src/main/java/io/holoinsight/server/common/dao/entity/TraceAgentConfigurationDOExample.java, server/common/common-dao-gen/src/main/java/io/holoinsight/server/common/dao/mapper/TraceAgentConfigurationDOMapper.java, server/common/common-dao-gen/src/main/resources/sqlmap/TraceAgentConfigurationDOMapper.xml, server/extension/extension-common-flyway/src/main/resources/db/migration/V17__230821_ADD_trace_agent_configuration_COLUMN.sql, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/TraceAgentConfiguration.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/TraceAgentConfigurationServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/TraceAgentFacadeImpl.java
=> fix: add creator/modifier for trace agent configuration

server/common/common-service/src/main/java/io/holoinsight/server/common/service/SuperCache.java, server/home/home-common/src/main/java/io/holoinsight/server/home/common/util/CookieUtils.java, server/home/home-common/src/main/java/io/holoinsight/server/home/common/util/scope/MonitorCookieUtil.java, server/home/home-common/src/main/java/io/holoinsight/server/home/common/util/scope/MonitorScope.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/GaeaSqlTaskUtil.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictKey.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictUtil.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/TenantInitService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/agent/AgentLogTailService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/DefaultTenantInitServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/InitFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/MetaFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/SearchFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/SysFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/UserFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/UserFavoriteFacadeImpl.java
Closes #
1. add environment in ### **MonitorScope**
2. add time layout of log parse in Log monitoring
=> refactor(home): add environment in MonitorScope

server/gateway/gateway-boot/src/main/java/io/holoinsight/server/gateway/bootstrap/HoloinsightGatewayConfiguration.java
=> fix: fix trace error

server/extension/extension-common-flyway/src/main/resources/db/migration/V18__230822_ADD_alarm_history_COLUMN.sql, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertNotifyHandler.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertSaveHistoryHandler.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/DefaultAlertNotifyHandler.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/converter/AlarmHistoryConverter.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/converter/AlarmHistoryDetailConverter.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/AlarmHistory.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/AlarmHistoryDetail.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlarmHistoryDTO.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlarmHistoryDetailDTO.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlarmHistoryDetailServiceImpl.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlarmHistoryServiceImpl.java
Closes #
Add `app` column in `alarm_history` and `alarm_history_detail`
- Users can search alarm history and alarm history detail by app
=> feat: add app column in alarm_history and alarm_history_detail

server/home/home-common/src/main/java/io/holoinsight/server/home/common/util/scope/MonitorCookieUtil.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/TenantInitService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/DefaultTenantInitServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java, server/query/query-service/src/main/java/io/holoinsight/server/query/service/impl/DefaultQueryServiceImpl.java
Closes #
Query schema by ql.
- Get tenant from MetricInfo in `server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/TenantInitService.java`
- Get schema by `describe table` in `server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java`
None
=> feat: query schema by ql

server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/SpanMetricEsStorage.java
Closes #
This PR is to fix the metering issue of APM.
This PR is to fix the metering issue of APM.
None.
=> fix: fix apm metering

scripts/all-in-one/build.sh, server/common/common/src/main/java/io/holoinsight/server/common/event/EventBusHolder.java, server/common/common/src/main/java/io/holoinsight/server/common/event/ModuleInitEvent.java, server/registry/registry-core/pom.xml, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/InitRunner.java, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/agent/AgentService.java, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/agent/AgentSyncer.java, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/collecttarget/CollectTargetService.java, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/collecttarget/TargetDebugService.java, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/dim/SlsConfig.java, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/dim/SlsDimConfiguration.java, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/dim/SlsLogstore.java, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/dim/SlsMetaSyncer.java, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/grpc/RegistryServiceForAgentImpl.java, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/template/ExecutorSelector.java
Closes #
- Sync sls shard meta
=> feat: sync sls shard meta

server/home/home-web/src/main/java/io/holoinsight/server/home/web/common/DashboardType.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/DashboardFacadeImpl.java
Closes #
Query dashboard by type and title.
- Add `/webapi/v1/dashboard/queryByType/{type}/{title}`
=> feat: query dashboard by type and title

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/AbstractLocalIntegrationPlugin.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/SpringBootPlugin.java
Closes #
1. fix collect table in integration component
=> fix(home): fix collect table in integration component

scripts/add-license.sh, server/common/common/src/main/java/io/holoinsight/server/common/JsonResult.java, server/query/query-grpc-gen/src/main/java/io/holoinsight/server/query/grpc/QueryServiceGrpc.java
Closes #
This PR is to support JsonResult to return failure results of generic type.
This PR is to support JsonResult to return failure results of generic type.
None.
=> fix: json result generic type

server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/dim/SlsConfig.java, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/dim/SlsMetaSyncer.java, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/lock/LockService.java, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/master/MasterDemo.java, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/master/MasterJson.java, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/master/MasterListener.java, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/master/MasterService.java
Closes #
- Only let one node synchronize the metadata of SLS. Avoid wasting resources.
=> refactor: sls sync once

server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/collecttarget/CollectTargetService.java
Closes #
- Refactor central agent assignment
=> refactor: central agent

server/apm/apm-server/apm-service/src/main/java/io/holoinsight/server/apm/server/service/impl/ApmMetricMaterializer.java, server/common/common-service/src/main/java/io/holoinsight/server/common/ctl/MonitorProductCode.java, server/common/common-service/src/main/java/io/holoinsight/server/common/ctl/ProductCtlConfiguration.java, server/common/common-service/src/main/java/io/holoinsight/server/common/ctl/ProductCtlService.java, server/common/common-service/src/main/java/io/holoinsight/server/common/ctl/ProductCtlServiceImpl.java, server/gateway/gateway-boot/src/main/java/io/holoinsight/server/gateway/bootstrap/HoloinsightGatewayConfiguration.java, server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/GatewayGrpcServiceImpl.java
Closes #
This PR is to support the start-stop control of the product.
=> feat: product ctl

server/common/common-service/src/main/java/io/holoinsight/server/common/ctl/ProductCtlService.java, server/common/common-service/src/main/java/io/holoinsight/server/common/ctl/ProductCtlServiceImpl.java, server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/GatewayGrpcServiceImpl.java
Closes #
This PR is to introduce caching to fix frequent database access when data is written.
=> fix: fix cache

server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/analysis/RelationAnalysis.java, server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/analysis/ServiceErrorAnalysis.java, server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/analysis/SlowSqlAnalysis.java, server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/common/IPublicAttr.java, server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/common/PublicAttr.java, server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/common/TransformAttr.java, server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/trace/SpanHandler.java, server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/auth/ApikeyWebController.java
Closes #
LINK [Holoinsight Collector PR](https://github.com/traas-stack/holoinsight-collector/pull/10)
=> feat: trace product close

server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/dto/AlarmBlockDTO.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/config/CollectType.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/AbstractCentralIntegrationPlugin.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/AbstractIntegrationPlugin.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/AbstractLocalIntegrationPlugin.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/MysqlPluginV2.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/SlsLogPlugin.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/AlertBlockService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlertBlockServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmBlockFacadeImpl.java
Closes #
1. add api interface of alarmBlock
2. add collectType of integration component
=> refactor(home): optimize alarmBlock

server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/agent/AgentEventService.java, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/dim/SlsMetaSyncer.java, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/master/MasterService.java
=> fix: fix sls meta

server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/builder/RPCTrafficSourceBuilder.java, server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/trace/SpanHandler.java
=> fix: fix apm NullPointerException in build relation

server/common/common-service/src/main/java/io/holoinsight/server/common/service/SuperCache.java, server/common/common-service/src/main/java/io/holoinsight/server/common/service/SuperCacheService.java, server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/QueryClientService.java
Closes #
Add workspace-MetricInfo map.
=> feat: add workspace metricinfo map

server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/DashboardFacadeImpl.java
Closes #
query dashboard by `miniapp` or `iot`
=> fix: query dashboard by type

server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/SpanEsStorage.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/utils/ApmGsonUtils.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/model/SpanDO.java, server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/common/TransformAttr.java, server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/trace/SpanHandler.java
=> feat: apm storage object tags

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictKey.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/listener/IntegrationGeneratedUpdateListener.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/PortCheckPlugin.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/MonitorTaskManager.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/TenantIntegrationGeneratedTask.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/crawler/SystemMetricCrawlerBuilder.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/IntegrationGeneratedFacadeImpl.java
Closes #
1. optimzie portcheck integration
=> refactor(home): optimzie portcheck integration

server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/SpanMetricEsStorage.java
Closes #
This PR is to fix query exceptions caused by illegal values.
This PR is to fix query exceptions caused by illegal values.
None.
=> fix: fix value null

server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/QueryClientService.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/AbstractMetricCrawlerBuilder.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/common/ParaCheckUtil.java
Closes #
Remove sql in query response.
=> fix: remove sql in response

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/GaeaSqlTaskUtil.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictKey.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/listener/IntegrationGeneratedUpdateListener.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/LogPlugin.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/IntegrationGeneratedServiceImpl.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/MonitorTaskManager.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/TenantIntegrationGeneratedTask.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/IntegrationGeneratedFacadeImpl.java
Closes #
1. fix integrationGeneratedFacade
2. fix IntegrationGeneratedUpdateListener
=> fix(home): fix integrationGeneratedFacade

server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/trace/SpanHandler.java, server/common/common-service/src/main/java/io/holoinsight/server/common/ctl/ProductCtlConfiguration.java, server/common/common-service/src/main/java/io/holoinsight/server/common/ctl/ProductStatusService.java, server/common/common-service/src/main/java/io/holoinsight/server/common/ctl/ProductStatusServiceImpl.java, server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/auth/ApikeyWebController.java, server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/GatewayGrpcServiceImpl.java
Closes #
Rename `ProductCtlService` as `ProductStatusService`.
Rename `ProductCtlService` as `ProductStatusService`.
=> fix: fix product ctl

server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/IntegrationGeneratedFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/filter/Step3AuthFilter.java
Closes #
1. fix horizontal overstep
=> fix: fix horizontal overstep

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictKey.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/TraceAgentFacadeImpl.java
=> feat: add trace agent version for trace guide

server/home/home-boot/src/main/java/io/holoinsight/server/home/bootstrap/HoloinsightHomeConfiguration.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/MetricInfoCheckService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/MetricInfoCheckServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/MetricInfoFacadeImpl.java
Closes #
Query MetricInfo by workspace.
- `server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/MetricInfoCheckService.java` check if a workspace is required.
=> feat: query MetricInfo by workspace

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/listener/IntegrationPluginUpdateListener.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/AbstractCentralIntegrationPlugin.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/AbstractIntegrationPlugin.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/AbstractLocalIntegrationPlugin.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/LogPlugin.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/MysqlPluginV2.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/TenantInitService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/DefaultTenantInitServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmRuleFacadeImpl.java
Closes #
1.  fix LogPatternPlugin
2. fix horizontal overstep in alarmRuleUpdate
=> fix(home): fix LogPatternPlugin

deploy/examples/k8s/base/collector.yaml, test/scenes/common/collector-config.yml
=> feat: open collector datadog receiver for test demo

server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/GatewayGrpcServiceImpl.java, server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/GatewayHook.java, server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/GatewayHookManager.java
Closes #
Add gateway hook for internal extension.
- Add gateway hook for internal extension
=> feat: add gateway hook

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/GetSubscriptionHandler.java
Closes #
Enable alarm block for empty tag situtations.
- Blocking alarm notification for empty tag config in alarm block.
None.
=> fix: alarm block

server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/model/WriteMetricsParam.java
Closes #
This PR is an indicator of whether writing parameter settings is allowed for free.
This PR is an indicator of whether writing parameter settings is allowed for free.
=> feat: allow free writing

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/ClusterTaskServiceImpl.java
Closes #
Fix cluster task period
=> fix: cluster task period

server/common/common-service/src/main/java/io/holoinsight/server/common/ctl/ProductCtlServiceImpl.java
Closes #
This PR is to fix the expired status caused by cache.
=> fix: fix product ctl status load db

server/apm/apm-boot/src/main/java/io/holoinsight/server/apm/bootstrap/HoloinsightApmConfiguration.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/HoloinsightEsConfiguration.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/SpanMetricEsStorage.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/TraceAgentFacadeImpl.java
=> fix: fix param check

test/scenes/common/base.yaml, test/scenes/common/status.sh
=> feat: export collector address in scenes

server/common/common-service/src/main/java/io/holoinsight/server/common/service/MetricInfoServiceImpl.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/LogPlugin.java
Closes #
1. fix tenant in metricTable for logPlugin
=> fix(home): fix tenant in metricTable for logPlugin

server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/SpanEsStorage.java
=> fix: fix build span NullPointException

server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/QueryClientService.java
Closes #
This PR is to set the gRPC in bound msg size to 40MB.
=> fix: grpc in bound msg size = 40MB

server/home/home-web/src/main/java/io/holoinsight/server/home/web/common/ParaCheckUtil.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java
Closes #
Check sql injection.
None.
=> fix: check sql injection

server/home/home-web/src/main/java/io/holoinsight/server/home/web/common/ParaCheckUtil.java
Closes #
Add `|` as valid character.
None.
=> fix: add valid character

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/CacheAlertTask.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/coordinator/AlertClusterService.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/coordinator/CoordinatorService.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/coordinator/OrderConfig.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/coordinator/OrderMap.java
Closes #
Force set order config for alert compute
None
=> feat: force set order config for alert compute

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/listener/IntegrationPluginUpdateListener.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/common/DashboardType.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/common/FacadeTemplateImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmChannelController.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmHistoryDetailFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmHistoryFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmRuleFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmWebhookFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlertNotifyRecordController.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/DashboardFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/GPTFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/IntegrationPluginFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/IntegrationProductFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/MarketplaceProductFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/OpenmetricsScraperFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/SysFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/UserinfoFacadeImpl.java
Closes #
1. fix security hole of the interface
2. optimize the error code returned by the interface
=> fix: fix security hole of interface

server/home/home-web/src/main/java/io/holoinsight/server/home/web/common/FacadeTemplateImpl.java
Closes #
1. Optimize interface error codes
=> fix: optimize interface errorcode

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/TenantInitService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/DefaultTenantInitServiceImpl.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/MetricCrawlerConstant.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/crawler/TenantMetricCrawlerTaskJob.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/CustomPluginFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/SysFacadeImpl.java
Closes #
1. optimize crawlerTaskJob, added the update comparison function
=> refactor(home): optimize crawlerTaskJob

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/log/LogCountRequest.java
=> feat: rename log path

server/common/common-dao/src/main/java/io/holoinsight/server/common/dao/entity/MonitorInstance.java, server/common/common-dao/src/main/java/io/holoinsight/server/common/dao/entity/MonitorInstanceCfg.java, server/common/common-dao/src/main/java/io/holoinsight/server/common/dao/entity/MonitorInstanceType.java, server/common/common-dao/src/main/java/io/holoinsight/server/common/dao/mapper/MonitorInstanceMapper.java, server/common/common-service/src/main/java/io/holoinsight/server/common/ctl/ProductCtlAction.java, server/common/common-service/src/main/java/io/holoinsight/server/common/ctl/ProductCtlServiceImpl.java, server/common/common-service/src/main/java/io/holoinsight/server/common/service/CommonServiceAutoConfiguration.java, server/common/common-service/src/main/java/io/holoinsight/server/common/service/MonitorInstanceService.java, server/common/common-service/src/main/java/io/holoinsight/server/common/service/MonitorInstanceServiceImpl.java, server/extension/extension-common-flyway/src/main/resources/db/migration/V21__231012_CREATE_monitor_instance_TABLE.sql, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertNotifyHandler.java
Closes #
This PR is to auto control product status.
=> feat: auto ctl

server/holoinsight-dependencies/pom.xml
Closes #
1. update version of aliyun-log
=> fix: update version aliyun-log

server/extension/extension-common-flyway/src/main/resources/db/migration/V22__231011_CREATE_agg_TABLE.sql
=> chore: add agg sql

server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/conf/GroupBy.java, server/agg/agg-executor-api/src/main/java/io/holoinsight/server/agg/v1/executor/output/BatchSerdes.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/AggExecutorAutoConfiguration.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/AggExecutorConfig.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/ExecutorManager.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/XParserUtils.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/output/AsyncOutput.java, server/extension/extension-common-flyway/src/main/resources/db/migration/V22__231011_CREATE_agg_TABLE.sql
Closes #
- Writing to kafka failed because the size exceeded the limit.
- Increase the maximum message limit of kafka
=> fix: fix kafka message size

server/common/common-service/src/main/java/io/holoinsight/server/common/ctl/ProductCtlServiceImpl.java, server/common/common-service/src/main/java/io/holoinsight/server/common/service/MonitorInstanceService.java, server/common/common-service/src/main/java/io/holoinsight/server/common/service/MonitorInstanceServiceImpl.java
Closes #
This PR is to fix exception of product auto closing.
=> feat: auto close

server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmBlockFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmGroupFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmSubscribeFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/ParameterSecurityService.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/ParameterSecurityServiceImpl.java
Closes #
Fix horizontal security
Fix:
- alarm block facade
- alarm group facade
- alarm subscriber facade
None
=> fix: horizontal security

server/home/home-common/src/main/java/io/holoinsight/server/home/common/util/scope/MonitorScope.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/access/AccessConfigService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/access/MonitorAccessService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/access/RateLimitService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/access/model/AccessConfig.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/access/model/MonitorAccessConfig.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/MetricInfoCheckService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/MetricInfoCheckServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmRuleFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/MetricInfoFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/filter/Step4AccessLogFilter.java
Closes #
1. optimize authFilter
=> refactor(home): optimize authFilter

server/agg/agg-dispatcher/src/main/java/io/holoinsight/server/agg/v1/dispatcher/AggDispatcherAutoConfiguration.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/AggExecutorAutoConfiguration.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/Group.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/XSelect.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/output/AsyncOutput.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/output/XConsoleOutput.java
Closes #
- Remove hardcoding about console output
- Refactor duplicate code
- Add switches for mock code
=> refactor: refactor aggregation output

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/common/http/HttpProxy.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AbstractUniformInspectRunningRule.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AlertTaskCompute.java
=> fix: alert compute await

server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmGroupFacadeImpl.java
=> fix: user check

server/agg/agg-boot/src/main/java/io/holoinsight/server/agg/v1/executor/executor/MetricStorageOutput.java, server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/AggProperties.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/output/AsyncOutput.java
=> fix: agg output

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictKey.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/TenantIntegrationGeneratedTask.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/CustomPluginFacadeImpl.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/CustomPluginFacadeIT.java
=> refactor(home): optimize integration_generated

server/common/common-service/src/main/java/io/holoinsight/server/common/config/ScheduleLoadTask.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertSaveHistoryHandler.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/GetSubscriptionHandler.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/converter/DoConvert.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/coordinator/CoordinatorService.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/coordinator/OrderMap.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/converter/AlarmHistoryConverter.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlarmHistoryDTO.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlertHistoryExtra.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlertRuleExtra.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlertSilenceConfig.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/InspectConfig.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/emuns/PeriodType.java, server/home/home-facade/src/test/java/io/holoinsight/server/home/facade/AlertSilenceConfigTest.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmGroupFacadeImpl.java
Closes #
Alert can keep silence.
=> feat: alert silence

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/listener/IntegrationPluginUpdateListener.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/LogPlugin.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/CustomPluginFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/FolderFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/UserFavoriteFacadeImpl.java
=> fix(home): fix security vulnerabilities

server/agg/agg-boot/src/main/java/io/holoinsight/server/agg/v1/executor/executor/MetricStorageOutput.java, server/agg/agg-executor-api/src/main/java/io/holoinsight/server/agg/v1/executor/output/WindowStat.java, server/agg/agg-executor-api/src/main/java/io/holoinsight/server/agg/v1/executor/output/XOutput.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/AggTaskExecutor.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/state/AggWindowState.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/state/StatePbConverter.java
Closes #
- Add time window statistics
- Move input into window statistics
=> refactor: agg window stat

server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/conf/OutputItem.java, server/agg/agg-executor/pom.xml, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/AggExecutorAutoConfiguration.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/AggTaskExecutor.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/XParserUtils.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/service/AggTaskV1Syncer.java
Closes #
- Supports topn output after aggregation
=> feat: agg topn

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AbstractUniformInspectRunningRule.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlertTemplateField.java
Closes #
Add tenant name, workspace name, pid in alert notification.
=> feat: alert pid

server/agg/agg-boot/src/main/java/io/holoinsight/server/agg/v1/executor/executor/MetricStorageOutput.java, server/agg/agg-executor-api/pom.xml, server/agg/agg-executor-api/src/main/java/io/holoinsight/server/agg/v1/executor/output/AggStringLookup.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/output/XConsoleOutput.java, server/holoinsight-dependencies/pom.xml
Closes #
- Agg output metric name supports format
=> feat: agg metric name format

server/home/home-common/src/main/java/io/holoinsight/server/home/common/util/scope/RequestContext.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/log/LogCountResponse.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/log/LogHistogramCount.java
=> refactor(home): add histogramLogCount

server/home/home-common/src/main/java/io/holoinsight/server/home/common/util/scope/RequestContext.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/log/LogCountResponse.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/log/LogHistogramCount.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/FolderFacadeImpl.java
=> refactor(home): optimize folderFacadeImpl

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AbstractUniformInspectRunningRule.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmGroupFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmSubscribeFacadeImpl.java
Closes #
Check group parameter.
=> feat: group parameter check

server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/Executor.java
Closes #
According to the documentation of ConsumerRebalanceListener, onPartitionsXxx methods only notify the user that partitions have changed, and the user cannot reject these changes by throwing exceptions.
In the original code, we had several places where exceptions were thrown.  Although these codes do enter an abnormal state, which may be caused by a disconnection from the network. But we should not throw exceptions, but try to re-enter the correct state.
In the original code, we had several places where exceptions were thrown. I removed them to make them more compatible.
=> fix: no exception in kafka rebalance listener

server/home/home-web/src/main/java/io/holoinsight/server/home/web/common/ParaCheckUtil.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmBlockFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmDingDingRobotFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmGroupFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmRuleFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmWebhookFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/ApiKeyFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/CustomPluginFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/DashboardFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/FolderFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/IntegrationGeneratedFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/IntegrationPluginFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/OpenmetricsScraperFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/UserFavoriteFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/UserinfoFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/UserinfoVerificationFacadeImpl.java
=> fix(home): fix security hole of create request

server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/ExecutorManager.java
=> chore: agg log

server/common/common/src/main/java/io/holoinsight/server/common/UtilMisc.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictKey.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictUtil.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/config/RestAuthUtil.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/filter/Step2IdentityFilter.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/filter/Step3AuthFilter.java
=> refactor(home): optimize filters

server/home/home-common/src/main/java/io/holoinsight/server/home/common/util/ResultCodeEnum.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/IntegrationPluginFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/filter/Step3AuthFilter.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/IntegrationPluginFacadeIT.java
=> fix: optimize return code in authfilter

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/event/AlertNotify.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/event/AlertNotifyRequest.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertNotifyHandler.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/DefaultAlertNotifyHandler.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/GetSubscriptionHandler.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlertTemplateField.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/NotificationTemplate.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/TemplateValue.java
Closes #
Add ip and  hostname in alert notification
=> feat: add ip and hostname in alert notification

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictKey.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictUtil.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/IntegrationPluginServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/DisplayMenuFacadeImpl.java
=> fix: fix displaymenu

server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/MeterService.java
Closes #
Add meter service interface for detail
=> feat: meter for detail

server/common/common/src/main/java/io/holoinsight/server/common/UtilMisc.java, server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/MeterService.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/BaseFacade.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/CustomPluginFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/UserFavoriteFacadeImpl.java
=> fix: fix redos vulenrability in logmonitor

server/common/common/src/main/java/io/holoinsight/server/common/UtilMisc.java
=> fix: shutdown thread executor

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/GetSubscriptionHandler.java
Closes #
Fix alert silence for default mode
=> fix: alert silence

server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/collecttarget/CollectTargetService.java
Closes #
Fix npe when building target
=> fix: fix npe when building target

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertSaveHistoryHandler.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/event/RecordSucOrFailNotify.java
Closes #
Fix alert compute finish in advance.
=> fix: alert return in advance

server/common/common-service/pom.xml, server/common/common-service/src/main/java/io/holoinsight/server/common/ctl/MonitorProductCode.java, server/common/common-service/src/main/java/io/holoinsight/server/common/ctl/ProductCtlService.java, server/common/common-service/src/main/java/io/holoinsight/server/common/ctl/ProductCtlServiceImpl.java, server/common/common-service/src/main/java/io/holoinsight/server/common/service/AccessRecordService.java, server/common/common-service/src/main/java/io/holoinsight/server/common/service/SuperCache.java, server/common/common-service/src/main/java/io/holoinsight/server/common/service/SuperCacheService.java, server/extension/extension-storage-ceresdbx/src/main/java/io/holoinsight/server/extension/ceresdbx/CeresdbxMetricStorage.java, server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/MetricMeterService.java, server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/GatewayGrpcServiceImpl.java, server/home/home-boot/src/main/java/io/holoinsight/server/home/bootstrap/HoloinsightHomeConfiguration.java, server/home/home-service/pom.xml, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/access/AccessConfigService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/access/AccessRecordService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/access/MonitorAccessService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/access/model/AccessConfig.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/access/model/MonitorAccessConfig.java
Closes #
This PR is to enable the metering of openapi invoking.
=> feat: openapi meter

server/home/home-task/src/main/java/io/holoinsight/server/home/task/MetricCrawlerConstant.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/crawler/SystemMetricCrawlerBuilder.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/IntegrationGeneratedFacadeImpl.java
=> refactor(home): optimize metricCrawler

server/common/common-service/src/main/java/io/holoinsight/server/common/ctl/ProductCtlServiceImpl.java
Closes #
This PR is to add log when the product status is changed.
=> feat: add product ctl log

server/agg/agg-dispatcher/src/main/java/io/holoinsight/server/agg/v1/dispatcher/AggDispatcher.java, server/agg/agg-dispatcher/src/main/java/io/holoinsight/server/agg/v1/dispatcher/AggDispatcherMockDataGenerator.java, server/agg/agg-dispatcher/src/main/java/io/holoinsight/server/agg/v1/dispatcher/AggGatewayHook.java, server/extension/extension-storage-ceresdbx/src/main/java/io/holoinsight/server/extension/ceresdbx/CeresdbDetailsStorage.java, server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/DetailsStorage.java, server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/MetricMeterService.java, server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/NoopDetailsStorage.java, server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/model/Header.java, server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/model/Row.java, server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/model/Table.java, server/gateway/gateway-boot/src/main/java/io/holoinsight/server/gateway/bootstrap/HoloinsightGatewayConfiguration.java, server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/DetailsStorageService.java, server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/GatewayGrpcServiceImpl.java, server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/GatewayHook.java, server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/TaskResultUtils.java
Closes #
- Write details datum to details storage
- Add CeresDB based details storage
=> feat: add details storage

server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/DateUtil.java
Closes #
Add yyyy-MM-dd+HH:mm:ss format in dateUtil
=> feat: add yyyy-MM-dd+HH:mm:ss format in dateUtil

server/gateway/gateway-core/pom.xml, server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/GatewayMetaServiceImpl.java, server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/GatewayGrpcServiceImpl.java, server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/GatewayHook.java, server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/GatewayHookManager.java, server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/GatewayMetaService.java
Closes #
- Add gateway meta service
- Add processV1 method in GatewayHook
=> feat: add gateway meta service

server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/AlarmBlock.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/AlarmGroup.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/AlarmHistory.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/AlarmHistoryDetail.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/AlarmRule.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/AlarmSubscribe.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/AlarmWebhook.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/AlertNotifyRecord.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/GaeaCollectConfig.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/MetaTable.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/UserFavorite.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/Userinfo.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/UserinfoVerification.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/dto/AlarmBlockDTO.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/dto/AlarmWebhookDTO.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmSubscribeFacadeImpl.java
=> fix: fix javax.persistence.Id

server/home/home-boot/src/main/java/io/holoinsight/server/home/bootstrap/HoloinsightHomeConfiguration.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/dto/AlarmBlockDTO.java, server/home/home-facade/pom.xml, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlarmRuleDTO.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/ApiSecurity.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/utils/ApiSecurityService.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/utils/CheckCategory.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/utils/CreateCheck.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/utils/FieldCheck.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/utils/ParaCheckUtil.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/utils/SecurityMethodCategory.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/utils/UpdateCheck.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/common/ApiSecurityFactory.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/common/SecurityResource.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmBlockFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmDingDingRobotFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmRuleFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/BaseFacade.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/ApiSecurityServiceImpl.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AlertRuleIT.java
Closes #
Providing api security check with simple code.
Using annotation to check api security.
None
=> feat: api security

server/registry/registry-model/src/main/java/io/holoinsight/server/registry/model/From.java
=> docs: add logPath doc

server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/RequestContextAdapter.java, server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/RequestContextAdapterImpl.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/dto/AlarmBlockDTO.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlarmRuleDTO.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/ApiSecurity.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/utils/CheckCategory.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/utils/ExistCheck.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/utils/FieldCheck.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/utils/ParaCheckUtil.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/utils/ReadCheck.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/common/ApiSecurityFactory.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmBlockFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmRuleFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/BaseFacade.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java
Closes #
Optimize api security
=> feat: optimize api security

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/log/LogQueryResponse.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/CustomPluginFacadeImpl.java
=> fix(home): fix logmonitor

server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java
Closes #
Get timestamp name from tsdb
=> feat: get timestamp name from tsdb

server/query/query-service/src/main/java/io/holoinsight/server/query/service/impl/DefaultQueryServiceImpl.java
Closes #
Fix NPE in detail query
=> fix: NPE in detail query

README-CN.md, README.md
=> fix: modify Holoinsight icon

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/compute/ComputeTaskPackage.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/event/AlertNotify.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertNotifyHandler.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertSaveHistoryHandler.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/GatewayService.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/GetSubscriptionHandler.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AbstractUniformInspectRunningRule.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AlertTaskCompute.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/data/AlarmDataSet.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/event/RecordSucOrFailNotify.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/AlertTaskScheduler.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/CacheAlertTask.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/converter/AlertNotifyRecordConverter.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/transformer/AlertNotifyErrorCodeMapper.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/transformer/AlertNotifyStageMapper.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/transformer/AlertNotifyUserMapper.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlertNotifyRecordDTO.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/NotifyErrorMsg.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/AlertNotifyRecordService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlertNotifyRecordServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java
=> refactor(alarm): optimize alertNotifyRecord

server/common/common-service/src/main/java/io/holoinsight/server/common/ctl/MonitorProductCode.java, server/common/common-service/src/main/java/io/holoinsight/server/common/ctl/ProductCtlServiceImpl.java, server/common/common/src/main/java/io/holoinsight/server/common/DateUtil.java, server/extension/extension-common-flyway/src/main/resources/db/migration/V24__231221_ADD_alert_notify_record_INDEX.sql
=> feat(home): add notifyChannel metering

scripts/deploy/build-and-replace-pod.sh, server/all-in-one/all-in-one-bootstrap/src/main/java/io/holoinsight/server/allinone/bootstrap/HoloinsightAllInOneBootstrap.java, server/all-in-one/all-in-one-bootstrap/src/main/resources/config/application.yaml
Closes #
We are not currently using mongodb, but its initialization process will report an error.
- Disable mongodb AutoConfgiuration
=> fix: disable mongodb autoconfiguration

server/common/common-service/src/main/java/io/holoinsight/server/common/config/EnvironmentProperties.java, server/home/home-common/pom.xml, server/home/home-common/src/main/java/io/holoinsight/server/home/common/util/http/ByteUtil.java, server/home/home-common/src/main/java/io/holoinsight/server/home/common/util/http/HttpAsync.java, server/home/home-common/src/main/java/io/holoinsight/server/home/common/util/http/HttpException.java, server/home/home-common/src/main/java/io/holoinsight/server/home/common/util/http/HttpProxy.java, server/home/home-common/src/main/java/io/holoinsight/server/home/common/util/http/Util.java, server/home/home-common/src/main/java/io/holoinsight/server/home/common/util/http/XHttpRequest.java, server/home/home-common/src/main/java/io/holoinsight/server/home/common/util/http/XHttpResponse.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/gpt/GptService.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/GPTFacadeImpl.java
=> feat: add holoinsight-gpt interface

server/common/common-dao/src/main/java/io/holoinsight/server/common/dao/entity/MonitorInstance.java, server/extension/extension-common-flyway/src/main/resources/db/migration/V25__231228_ADD_monitor_instance_COLUMN.sql, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java
Closes #
Add more choices of period of time.
=> feat: period of time

server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/query/QueryDetailResponse.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/utils/ApiSecurityService.java, server/home/home-web/pom.xml, server/home/home-web/src/main/java/io/holoinsight/server/home/web/config/WebMvcConfig.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmRuleFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/ApiSecurityServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/CheckTargetCollector.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/CheckTypeEnum.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/ContentTargetCollector.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/LevelAuthContentGet.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/LevelAuthorizationAccess.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/LevelAuthorizationCheck.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/LevelAuthorizationCheckException.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/LevelAuthorizationDecisionManager.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/LevelAuthorizationInterceptor.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/LevelAuthorizationMetaData.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/LevelAuthorizationMetadataSource.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/ParameterParseUtil.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/SecurityMetaData.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/custom/AlarmRuleLevelAuthorizationChecker.java
Closes #
Api security check by interceptor
None
=> feat: api security check

server/common/common-service/src/main/java/io/holoinsight/server/common/service/SuperCacheService.java
Closes #
Increase super cache period to 1min
None
=> fix: supercache 60s period

server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/DetailsStorageService.java
Closes #
- detail data with empty fields are allowed
=> fix: detail data with empty fields are allowed

server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/service/DBCoreServiceSwitcher.java
=> fix: fix dbCoreService switch

server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/model/DetailResult.java
Closes #
Fix NPE in DetailResult
=> fix: npe in detailResult

server/common/common-service/src/main/java/io/holoinsight/server/common/ctl/ProductCtlServiceImpl.java, server/common/common-service/src/main/java/io/holoinsight/server/common/service/MetricInfoServiceImpl.java, server/gateway/gateway-grpc-gen/src/main/java/prometheus/Prometheus.java, server/gateway/gateway-grpc-gen/src/main/java/prometheus/PrometheusTypes.java, server/home/home-common/src/main/java/io/holoinsight/server/home/common/util/ResultCodeEnum.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictKey.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java
=> fix: fix pmd

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/gpt/GptService.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/GPTFacadeImpl.java
=> fix: fix gpt interface error

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/listener/IntegrationGeneratedUpdateListener.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/listener/IntegrationPluginUpdateListener.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/LogPlugin.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/LogPluginUtil.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/MultiLogPlugin.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/TenantIntegrationGeneratedTask.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/CustomPluginFacadeImpl.java
=> fix: fix multilog plugin of integration

server/apm/apm-common/src/main/java/io/holoinsight/server/apm/common/model/storage/annotation/ModelAnnotation.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/HoloinsightEsConfiguration.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/ttl/EsDataCleaner.java
Closes #
`holoinsight.storage.elasticsearch.ttl`
=> feat: apm ttl

server/common/common-service/src/main/java/io/holoinsight/server/common/service/SuperCacheService.java, server/extension/extension-common-flyway/src/main/resources/db/migration/V26__240124_ADD_alarm_rule_COLUMN.sql, server/extension/extension-common-flyway/src/main/resources/db/migration/V27__240124_CREATE_alert_notification_template_TABLE.sql, server/gateway/gateway-grpc-gen/src/main/java/prometheus/PrometheusTypes.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/converter/AlertNotificationTemplateConverter.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/mapper/AlertNotificationTemplateMapper.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/AlarmRule.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/AlertNotificationTemplate.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlarmRuleDTO.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlertNotificationTemplateDTO.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/NotificationTemplate.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlertNotificationTemplateFacadeImpl.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/LogMonitoringMultilineIT.java
Closes #
Add alert notification template.
=> feat: alert template

server/extension/extension-storage-ceresdbx/src/main/java/io/holoinsight/server/extension/ceresdbx/CeresdbDetailsStorage.java, server/extension/extension-storage-ceresdbx/src/main/java/io/holoinsight/server/extension/ceresdbx/CeresdbxMetricStorage.java, server/extension/extension-storage-ceresdbx/src/main/java/io/holoinsight/server/extension/ceresdbx/HoloinsightCeresdbxConfiguration.java, server/extension/extension-storage-ceresdbx/src/main/java/io/holoinsight/server/extension/ceresdbx/MetricMeterServiceImpl.java, server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/MetricMeterService.java, server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/DetailsStorageService.java, server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/GatewayGrpcServiceImpl.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertSaveHistoryHandler.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/NullValueTracker.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/data/load/AIAlarmLoadData.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/data/load/RuleAlarmLoadData.java, server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/QueryClientService.java, server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/query/QueryResponse.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictKey.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictUtil.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/MonitorTaskManager.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java
Closes #
1. optimize metric metering switch
2. optimize result of dataquery
=> refactor: optimize metric metering switch

server/extension/extension-common-flyway/src/main/resources/db/migration/V28__240125_ADD_alert_notification_template_COLUMN.sql, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/event/AlertNotifyRequest.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/GatewayService.java, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/AlertNotificationTemplate.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlertNotificationTemplateDTO.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlertRuleExtra.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/NotificationTemplate.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlertTemplateFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/custom/AlertTemplateFacadeImplChecker.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/LogMonitoringMultilineIT.java
=> feat: dingtalk notification template

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/CacheAlertTask.java, test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/LogMonitoringMultilineIT.java
=> fix: alert cache retry

server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java, server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/common/FilterUtil.java, server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/service/hashmap/HashMapDataCoreService.java
=> fix: fix index problem of metadata

server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/utils/ParaCheckUtil.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlertTemplateFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/custom/AlertTemplateFacadeImplChecker.java
=> fix: alert template

server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/conf/GroupBy.java, server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/conf/GroupByItem.java, server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/conf/JoinMeta.java, server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/dict/Dict.java, server/agg/agg-executor-api/src/main/java/io/holoinsight/server/agg/v1/executor/executor/FixedSizeTags.java, server/agg/agg-executor-api/src/main/java/io/holoinsight/server/agg/v1/executor/output/WindowStat.java, server/agg/agg-executor/pom.xml, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/AggExecutorAutoConfiguration.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/AggMetaService.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/AggMetaServiceImpl.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/AggTaskExecutor.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/Executor.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/ExecutorManager.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/PartitionProcessor.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/StaticAggMetaService.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/state/AggWindowState.java, server/holoinsight-dependencies/pom.xml
Closes #
supports meta join in agg
=> feat: supports meta join in agg

server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlertTemplateFacadeImpl.java
=> fix: alert template parse

server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlertTemplateFacadeImpl.java
=> fix: alert template check

server/extension/extension-common-flyway/src/main/resources/db/migration/V32__240208_ADD_alarm_history_COLUMN.sql, server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/AlarmHistory.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlarmHistoryDTO.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/listener/AlarmRuleHistoryUpdateListener.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/listener/AlarmRuleUpdateListener.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/AlarmHistoryService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlarmHistoryServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmHistoryFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/custom/AbstractResourceChecker.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/custom/AlarmDingDingRobotFacadeImplChecker.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/custom/AlarmHistoryFacadeImplChecker.java
=> feat: alarm history delete

server/common/common-service/src/main/java/io/holoinsight/server/common/service/SuperCacheService.java
=> fix: fix monitorinstance in supercacheservice

server/agg/agg-boot/src/main/java/io/holoinsight/server/agg/v1/executor/executor/MetricStorageOutput.java, server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/conf/AggFunc.java, server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/conf/AggTask.java, server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/conf/Extension.java, server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/conf/OutputField.java, server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/data/InDataNodeDataAccessor.java, server/agg/agg-dispatcher/pom.xml, server/agg/agg-dispatcher/src/main/java/io/holoinsight/server/agg/v1/dispatcher/AggDispatcher.java, server/agg/agg-dispatcher/src/main/java/io/holoinsight/server/agg/v1/dispatcher/AggDispatcherAutoConfiguration.java, server/agg/agg-dispatcher/src/main/java/io/holoinsight/server/agg/v1/dispatcher/AggSpanStorageHook.java, server/agg/agg-dispatcher/src/main/java/io/holoinsight/server/agg/v1/dispatcher/AggTaskV1Syncer2.java, server/agg/agg-executor-api/src/main/java/io/holoinsight/server/agg/v1/executor/output/PercentileFinalValues.java, server/agg/agg-executor/pom.xml, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/AggTaskExecutor.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/GroupField.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/PercentileState.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/kryo/PercentileStateSerializer.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/output/AsyncOutput.java, server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/output/XConsoleOutput.java, server/apm/apm-boot/src/main/java/io/holoinsight/server/apm/bootstrap/HoloinsightApmConfiguration.java, server/apm/apm-server/apm-core/pom.xml, server/apm/apm-server/apm-core/src/main/java/io/holoinsight/server/apm/core/ApmConfig.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/postcal/MetricsManager.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/storage/SpanStorageHook.java, server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/storage/SpanStorageHookManager.java, server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/trace/SpanHandler.java, server/common/common/src/main/java/io/holoinsight/server/common/threadpool/ThreadPoolConfiguration.java, server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/model/Record.java
Closes #
- Supports pre-aggregation for spans
=> feat: apm agg

server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/UserFavoriteFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/ParameterSecurityService.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/ParameterSecurityServiceImpl.java
=> feat: checker

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/CacheAlertTask.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlertRuleServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/UserFavoriteFacadeImpl.java
=> fix: break

server/home/home-common/src/main/java/io/holoinsight/server/home/common/util/CommonThreadPool.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/TenantInitService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/DefaultTenantInitServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java
=> feat: batch query

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictKey.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java
=> fix: query schema

server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlertTemplateField.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlertTemplateFacadeImpl.java
=> fix: template fields

server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/AlarmSubscribe.java
=> feat: add sourceType for subscribe

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/config/CollectType.java, server/registry/registry-model/src/main/java/io/holoinsight/server/registry/model/integration/CollectMetricConf.java, server/registry/registry-model/src/main/java/io/holoinsight/server/registry/model/integration/IntegrationTransForm.java, server/registry/registry-model/src/main/java/io/holoinsight/server/registry/model/integration/mysql/MysqlTaskV3.java, server/registry/registry-model/src/main/java/io/holoinsight/server/registry/model/integration/ob/ObTask.java
=> feat: support mysqlplugin of local collect

server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/RequestContextAdapter.java, server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/RequestContextAdapterImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlertTemplateFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/BaseFacade.java
=> feat: states facade

server/meta/meta-common/src/main/java/io/holoinsight/server/meta/common/util/ConstModel.java, server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/service/bitmap/AbstractMetaData.java, server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/service/bitmap/MetaColData.java, server/registry/registry-model/src/main/java/io/holoinsight/server/registry/model/Elect.java
=> refactor: support labels query of metaservice

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/data/AlarmDataSet.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/data/load/RuleAlarmLoadData.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/trigger/DataSource.java, server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/trigger/Trigger.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlertDingDingRobotServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmSubscribeFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/MetricInfoFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/custom/AlarmRuleLevelAuthorizationChecker.java
=> fix: workspace and tenant

server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/custom/AbstractResourceChecker.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/custom/AlarmRuleLevelAuthorizationChecker.java
=> fix: fix AlarmRuleLevelAuthorizationChecker

server/home/home-boot/src/main/java/io/holoinsight/server/home/bootstrap/HoloinsightHomeConfiguration.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/access/MonitorAccessService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictKey.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictUtil.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmWebhookFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/filter/Step2IdentityFilter.java
=> feat: webhook

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/CacheAlertTask.java, server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/QueryClientService.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmSubscribeFacadeImpl.java
=> fix: token auth security

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/CacheAlertTask.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/coordinator/CoordinatorService.java, server/home/home-alert/src/test/java/io/holoinsight/server/home/alert/service/task/coordinator/CoordinatorServiceTest.java
=> fix: alarm rule query

server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/GatewayGrpcServiceImpl.java, server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/GatewayHook.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/core/LogPluginUtil.java
=> fix: fix spm of logmonitor

server/common/common-service/src/main/java/io/holoinsight/server/common/config/KafkaProperties.java
=> fix: agg properties

server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/output/AsyncOutput.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/custom/AlarmRuleLevelAuthorizationChecker.java
=> fix: agg retry

server/agg/agg-dispatcher/src/main/java/io/holoinsight/server/agg/v1/dispatcher/AggDispatcher.java, server/common/common-service/src/main/java/io/holoinsight/server/common/service/impl/AlertSubscribeServiceImpl.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/GaeaCollectConfigService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/GaeaCollectConfigServiceImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmSubscribeFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/custom/AlarmRuleLevelAuthorizationChecker.java, server/registry/registry-model/src/main/java/io/holoinsight/server/registry/model/Output.java
=> refactor(home): change size of messages sent by kafka to 2M

server/home/home-task/src/main/java/io/holoinsight/server/home/task/crawler/ApmMetricCrawlerBuilder.java, server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/common/FilterUtil.java, server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/service/AbstractDataCoreService.java, server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/service/SqlDataCoreService.java, server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/service/hashmap/HashMapDataCoreService.java, test/demo/agg-example/apm-component.json, test/demo/agg-example/apm-endpoint.json, test/demo/agg-example/apm-service-endpoint-error.json, test/demo/agg-example/apm-service-error.json, test/demo/agg-example/apm-service-instance.json, test/demo/agg-example/apm-service.json, test/demo/agg-example/k8s_pod_agg1.json, test/demo/agg-example/k8s_pod_agg2.json, test/demo/agg-example/log-agg1.json, test/demo/agg-example/log-analysis-agg1.json, test/demo/gaea-example/logcollect1.json, test/demo/gaea-example/logcollect2.json
=> feat: add test case of logmonitor

server/common/common-dao/src/main/java/io/holoinsight/server/common/dao/entity/dto/alarm/trigger/CompareParam.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/common/ParaCheckUtil.java
=> refactor: add unit in alarmRule datasource

server/extension/extension-storage-ceresdbx/src/main/java/io/holoinsight/server/extension/ceresdbx/CeresdbxClientManager.java
=> fix: local document

server/extension/extension-storage-ceresdbx/src/main/java/io/holoinsight/server/extension/ceresdbx/CeresdbxMetricStorage.java
=> fix: facade

server/common/common-service/src/main/java/io/holoinsight/server/common/ctl/ProductCtlServiceImpl.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictKey.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictUtil.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java, test/scenes/common/base.yaml
=> refactor: open the gateway and registry port in docker-compose deployment

test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/apm/ApmAppMetricStatIT.java
=> fix: update apmIT

server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/custom/AlarmSubscribeFacadeImplChecker.java
=> fix: subscribe webhook

server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/custom/AlarmSubscribeFacadeImplChecker.java
=> fix: alarm subscribe notice type

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertSaveHistoryHandler.java
=> fix: log sample group by

server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertSaveHistoryHandler.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/UserinfoFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/custom/UserinfoFacadeImplChecker.java
=> feat: userinfo checker

server/common/common-dao/src/main/java/io/holoinsight/server/common/dao/converter/MonitorInstanceConfigConverter.java, server/common/common-dao/src/main/java/io/holoinsight/server/common/dao/entity/dto/MonitorInstanceDTO.java, server/common/common-dao/src/main/java/io/holoinsight/server/common/dao/transformer/MonitorInstanceCfgMapper.java, server/common/common-service/src/main/java/io/holoinsight/server/common/ctl/ProductCtlServiceImpl.java, server/common/common-service/src/main/java/io/holoinsight/server/common/service/MonitorInstanceService.java, server/common/common-service/src/main/java/io/holoinsight/server/common/service/impl/MonitorInstanceServiceImpl.java
=> refactor: optimize query of monitorInstance

server/common/common-service/src/main/java/io/holoinsight/server/common/service/impl/AlarmHistoryServiceImpl.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AbstractUniformInspectRunningRule.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/listener/AlarmRuleUpdateListener.java
=> fix: alarm history

server/agg/agg-dispatcher/src/main/java/io/holoinsight/server/agg/v1/dispatcher/AggDispatcher.java
=> fix: kafka send stat

server/apm/apm-common/src/main/java/io/holoinsight/server/apm/common/model/specification/OtlpMappings.java
=> fix: zsearch index

server/apm/apm-common/src/main/java/io/holoinsight/server/apm/common/model/specification/OtlpMappings.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/CacheAlertTask.java, server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/coordinator/CoordinatorService.java, server/home/home-alert/src/test/java/io/holoinsight/server/home/alert/service/task/coordinator/CoordinatorServiceTest.java
=> fix: alert task assign

server/common/common-dao/src/main/java/io/holoinsight/server/common/dao/entity/dto/NotificationTemplate.java
=> fix: alarm rule url

server/all-in-one/all-in-one-bootstrap/src/main/resources/config/application.yaml, server/common/common-dao-gen/src/main/resources/generatorConfig.xml, server/common/common-service/src/main/java/io/holoinsight/server/common/service/SuperCacheService.java, server/common/common/src/main/java/io/holoinsight/server/common/CipherUtils.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/SysFacadeImpl.java, server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/service/DBCoreServiceSwitcher.java, server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/service/hashmap/HashMapDataCoreService.java, server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/cluster/DbMemberProvider.java
=> refactor: optimize dbCoreServiceSwitcher

server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/TenantInitService.java, server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/DefaultTenantInitServiceImpl.java, server/home/home-task/src/main/java/io/holoinsight/server/home/task/TenantIntegrationGeneratedTask.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AgentFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/CustomPluginFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/InitFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/TraceAgentFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/TraceQueryFacadeImpl.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/ParameterSecurityService.java, server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/ParameterSecurityServiceImpl.java
=> refactor: optimize parameterSecurityChecker

.github/workflows/merge-gate.yml
=> fix: fix security vulnerabilities
