- server/home/home-common/src/main/java/io/holoinsight/server/home/common/util/scope/RequestContext.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/filter/Step2IdentityFilter.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/filter/Step3AuthFilter.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/filter/Step4AccessLogFilter.java
Closes #161 
When non-webapi external requests (like '/internal/api/gateway/agent/configuration/query'), key information such as apikey/tenant is not carried，at this point, npe will appear when going through step4AccessLogFilter ,
The step3AuthFilter filter will catch this exception，and then execute
> resp.sendError(HttpServletResponse.SC_UNAUTHORIZED, "auth check error, " + e.getMessage());
> log.error("{} auth check error, auth info: {}", RequestContext.getTrace(), J.toJson(J.toJson(RequestContext.getContext())), e);
But fininal also throws exception because of the npe and catch by step2IdentityFilter
> resp.sendError(HttpServletResponse.SC_UNAUTHORIZED, RequestContext.getTrace() + " identity error, " + e.getMessage());
Verify the npe in tracelog in step4AccessLogFilter，and then resolve …
> fix: repeat call sendError() in filters

- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/event/AlertNotify.java
- server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/NotificationTemplate.java
- server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/TemplateValue.java
- server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/emuns/AlertLevel.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmWebhookFacadeImpl.java
- Remove rule url and monitor link from markdown alert content, instead of actionCard button.
- Keep AlertLevel enum type in `TemplateValue`.
None.
e2e
> fix(home): fix dingtalk notification template

- server/common/common/pom.xml
- server/common/common/src/main/java/io/holoinsight/server/common/AddressUtil.java
- server/holoinsight-dependencies/pom.xml
Replace IPAddressUtil with Apache commons-validator, because sun.* packages has been removed from jdk 11
It's introduce a new package: commons-validator, if anyone concerned about it, can simply remove it and copy 2 files from source
No
No tests
> fix: replace IPAddressUtil with Apache commons-validator

- .github/workflows/build-docker-image.yml
- scripts/docker/Dockerfile
- scripts/docker/buildx.sh
Closes #173 
Supports building amd64/arm64v8 converged image using docker buildx.
Supports building amd64/arm64v8 converged image using docker buildx.
Build successfully in my M1 Mac and Linux.
```plain
#sh ./scripts/docker/buildx.sh
use /root/.docker/cli-plugins/buildx
[+] Building 0.9s (31/31) FINISHED
=> [internal] load build definition from Dockerfile                                                                                                                          0.0s
=> => transferring dockerfile: 32B                                                                                                                                           0.0s
=> [internal] load .dockerignore …
```
> feat: supports building amd64/arm64v8 converged image

- README-CN.md
- README.md
Closes #
The 'Quick Start' demo requires docker-compose V2.
The 'Quick Start' demo requires docker-compose V2.
No
> docs: quick start demo requires docker-compose V2

- README-CN.md
- README.md
- deploy/examples/docker-compose/docker-compose.sh
- deploy/examples/docker-compose/docker-compose.yaml
- deploy/examples/docker-compose/down.sh
- deploy/examples/docker-compose/up.sh
Closes #186
The 'Quick Start' demo requires docker compose version >= v1. 29 || >=v2.
When use docker compose V1, the cli is 'docker-compose'.
When use docker compose V2, the cli is 'docker compose'.
Automatically use `docker compose` when docker compose V2 installed.
Automatically use `docker-compose` when docker compose V1 installed.
No
Local test
docker compose V1
docker compose v2
> refactor: Quick Start demo supports docker compose v1.29 && v2

- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/SysFacadeImpl.java
Closes #193 
Add @TokenUrls("/webapi/sys/debug") in SysFacadeImpl
Allow token request to /sys/debug
> feat(home): enable debug interfaces (#193)

- server/common/common/src/main/java/io/holoinsight/server/common/DurationUtil.java
- server/common/common/src/test/java/io/holoinsight/server/common/DurationUtilTest.java
- server/query/query-service/src/main/java/io/holoinsight/server/query/service/impl/DefaultQueryServiceImpl.java
- server/query/query-service/src/main/java/io/holoinsight/server/query/service/impl/QueryStorageUtils.java
Closes #209 
Improve the parsing of string formats such as `dawnsample` to duration.
Added a `DurationUtil` for parsing the duration of the string format.
Users can use more duration formats that were not supported before.
Unit test [DurationUtilTest](https://github.com/xiangwanpeng/holoinsight/blob/feat/duration-utils/server/common/common/src/test/java/io/holoinsight/server/common/DurationUtilTest.java) passed.
> feat: improve duration parsing

- deploy/examples/docker-compose/docker-compose.yaml
- deploy/examples/k8s/overlays/example/wait-server.sh
Closes #
Mongo and CeresDB uses different healthcheck method.
For example:
1. CeresDB image contains `curl` luckily for healthcheck. If the image doesn't `curl` we have to use another method.
2. MongoDB 5 image contains a `mongosh` bin. We use it for healthcheck.
3. MongoDB 4 image doesn't contains a `mongosh`. So we have to use another healthcheck method.
They can actually use a unified and general healthcheck method. Port checking is enough for them.
Use simple port healthcheck for better compatibility, which is learning from [skywalking](https://github.com/apache/skywalking/blob/master/test/e2e-v2/cases/alarm/es/es-sharding/docker-compose.yml#L28)
No
Tests 'Quick Start' successfully in Linux and M1 mac.
> build: use simple port healthcheck for better compatibility

- server/all-in-one/all-in-one-bootstrap/src/main/java/io/holoinsight/server/allinone/bootstrap/HoloinsightAllInOneBootstrap.java
- server/all-in-one/all-in-one-bootstrap/src/main/resources/config/application.yaml
- server/all-in-one/all-in-one-bootstrap/src/main/resources/db/migration/V1__230301_INIT_DDL.sql
- server/all-in-one/all-in-one-bootstrap/src/main/resources/db/migration/V2__230301_Uniform_COLUMN.sql
- server/common/common-dao/src/main/java/io/holoinsight/server/common/dao/entity/FlywaySchemaHistory.java
- server/common/common-dao/src/main/java/io/holoinsight/server/common/dao/mapper/FlywaySchemaHistoryMapper.java
- server/common/common-service/pom.xml
- server/common/common-service/src/main/java/io/holoinsight/server/common/service/flyway/FlywayConfiguration.java
- server/common/common-service/src/main/java/io/holoinsight/server/common/service/flyway/FlywayProperties.java
- server/common/common-service/src/main/java/io/holoinsight/server/common/service/flyway/FlywayService.java
- server/common/common-service/src/main/java/io/holoinsight/server/common/service/flyway/FlywaydbController.java
- server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/Cluster.java
- server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/UserOpLog.java
Closes #73 
We manage DDL manually in an internal document. This is easy to cause problems For example, missing DDL updates in some deployments, so we added flyway to manage sql scripts
1. The SQL script is located in server/all-in-one/all-in-one-bootstrap/src/main/resources/db/migration
- V1__230301_INIT_DDL.sql file records the initial table structure
- V2__230301_Uniform_COLUMN.sql correct the fields in different environments based on V1__230301_INIT_DDL.sql (if necessary)
- VX__YYMMDD_description.sql If there is any subsequent table structure or data correction, add it to this path according to this format, and the application will automatically take effect when it starts
2. Added some apis for sql version management operations, generally do not need to be manually executed, unless …
> feat: Support flyway

- server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlarmRuleDTO.java
- server/home/home-facade/src/test/java/io/holoinsight/server/home/facade/AlarmRuleDTOTest.java
- server/home/home-web/pom.xml
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmRuleFacadeImpl.java
- server/home/home-web/src/test/java/io/holoinsight/server/home/web/controller/AlarmRuleFacadeImplTest.java
Closes #234 
Using login name as filtering condition when users query alert rule in "I create" condition.
In the personal center users can use "I create" to filter alert rules.
`server/home/home-facade/src/test/java/io/holoinsight/server/home/facade/AlarmRuleDTOTest.java`
`server/home/home-web/src/test/java/io/holoinsight/server/home/web/controller/AlarmRuleFacadeImplTest.java`
> fix(home): fix alarm rule facade

- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/GaeaSqlTaskUtil.java
Closes #236 
Now the segmentation rule for blacklist filtering uses the log partitioning rule,  as a result, the configuration does not take effect.
> fix: Resolve problem that blackfilters in logmonitor take not effect

- server/common/common-service/src/main/java/io/holoinsight/server/common/service/FuseProtector.java
- server/common/common-service/src/main/java/io/holoinsight/server/common/service/HoloInsightCriticalException.java
- server/common/common-service/src/test/java/io/holoinsight/server/common/service/FuseProtectorTest.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/NotifyChain.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AlertTaskCompute.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/AlertTaskScheduler.java
Closes #240 
`FuseProtector` records the state at each step in the alert detection process, it provide assertions to help the caller to check whether the alert detection task completed successfully.
- Add `FuseProtector`
- Recording alert detection stat using `FuseProtector`
None.
Unit test: `server/common/common-service/src/test/java/io/holoinsight/server/common/service/FuseProtectorTest.java`
> feat(home): add fuse protector

- server/home/home-alert/pom.xml
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/CacheAlertTask.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/coordinator/CoordinatorService.java
- server/home/home-alert/src/test/java/io/holoinsight/server/home/alert/service/task/CacheAlertTaskTest.java
- server/home/home-alert/src/test/java/io/holoinsight/server/home/alert/service/task/coordinator/CoordinatorServiceTest.java
- server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlarmRuleDTO.java
Closes #244 
- Invoke `io.holoinsight.server.home.alert.service.task.CacheAlertTask#getAlertRule` separately according to ruleType.
- Calculate `pageSize` and `pageNum` separately according to ruleType.
None.
Unit tests:
- `server/home/home-alert/src/test/java/io/holoinsight/server/home/alert/service/task/CacheAlertTaskTest.java`
- `server/home/home-alert/src/test/java/io/holoinsight/server/home/alert/service/task/coordinator/CoordinatorServiceTest.java`
> feat(home): scheduling alert detection separately according to ruleType

- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/CustomPluginServiceImpl.java
Closes #
1. solve problem of deleting the collection configuration when deleting the log monitoring configuration
> fix: deleting the gaea collectconfig when deleting the logmonitor config

- server/apm/apm-server/apm-core/src/main/java/io/holoinsight/server/apm/core/installer/ModelInstallManager.java
- server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/HoloinsightEsConfiguration.java
- server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/installer/EsModelInstaller.java
- server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/RecordEsStorage.java
- server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/SpanEsStorage.java
- server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/ttl/EsDataCleaner.java
- server/apm/apm-server/apm-web/src/main/java/io/holoinsight/server/apm/web/initializer/ApmInitializer.java
Closes #
This PR is to make part of the code of Holoinsight can be reused to support more search engines compatible with the elasticsearch protocol.
- Redefine the elasticsearch client from a variable `esClient` to an overridable method `esClient()`. 
- Revised some elasticsearch storage logs, the engine is no longer hard-coded but prints the simple name of the current class.
- Some codes of `ModelInstallerMananger` are optimized.
- The startup failure of the module APM no longer affects the startup of Holoinsight.
None.
Validated on my local test environment.
> feat: optimize integration with elasticsearch

- .github/workflows/e2e-test.yml
- server/all-in-one/all-in-one-bootstrap/src/main/resources/config/application.yaml
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertNotifyHandler.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertSaveHistoryHandler.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/DefaultAlertNotifyHandler.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/DefaultGatewayService.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/GatewayService.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/GetSubscriptionHandler.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/main/AlertStarter.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/CacheAlertConfig.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/CacheAlertTask.java
- server/home/home-boot/src/main/java/io/holoinsight/server/home/bootstrap/HoloinsightHomeConfiguration.java
- test/server-e2e-test/pom.xml
- test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/AlertRuleIT.java
- test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/alert/AlertRuleIT.java
- test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/bootstrap/ITSets.java
Closes #212 
Add alert calculate handler.
- `AlertNotifyHandler` is responsible for assembling the parameters and fields required for the alert notification.
- `AlertSaveHistoryHandler` is responsible for saving the alert record in the database
- `GatewayService` is responsible for calling the notification chain and delivering the alert to each notification channel.
- `GetSubscriptionHandler` is responsible for getting the alerts subscription relationship.
None.
E2E test: test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/alert/AlertRuleIT.java
> fix(home): fix alert not work

- .github/workflows/e2e-test.yml
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/function/FunctionConfigParam.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AbstractUniformInspectRunningRule.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/BaseFunction.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/FunctionManager.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/PeriodAbs.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/PeriodRate.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/PeriodValue.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/Step.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/TriggerLogicNew.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/data/load/RuleAlarmLoadData.java
- server/home/home-alert/src/test/java/io/holoinsight/server/home/alert/service/calculate/CurrentTest.java
- server/home/home-alert/src/test/java/io/holoinsight/server/home/alert/service/calculate/PeriodAbsTest.java
- server/home/home-alert/src/test/java/io/holoinsight/server/home/alert/service/calculate/PeriodRateTest.java
- server/home/home-alert/src/test/java/io/holoinsight/server/home/alert/service/calculate/PeriodValueTest.java
- server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/DataResult.java
- server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/emuns/FunctionEnum.java
- server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/emuns/PeriodType.java
- server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/trigger/CompareConfig.java
- server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/trigger/Trigger.java
- test/scenes/scene-default/after.sh
- test/scenes/scene-default/log-alert-generator.py
- test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/AlertCalculateIT.java
- test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/bootstrap/ITSets.java
- test/server-e2e-test/src/test/resources/requests/AlertCalculateIT.json
Closes #270 
- `PeriodValue`: Detection of the rise and fall difference.
- `PeriodRate`: Detection of the rise and fall ratio relative to past values.
- `PeriodAbs`: Detection of the absolute value of the rise and fall difference.
User can choose more alert detection modes.
E2E: `test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/AlertCalculateIT.java`
Unit tests:
- `server/home/home-alert/src/test/java/io/holoinsight/server/home/alert/service/calculate/CurrentTest.java`
- `server/home/home-alert/src/test/java/io/holoinsight/server/home/alert/service/calculate/PeriodAbsTest.java`
- `server/home/home-alert/src/test/java/io/holoinsight/server/home/alert/service/calculate/PeriodValueTest.java`
- `server/home/home-alert/src/test/java/io/holoinsight/server/home/alert/service/calcu …
> feat(home): period alert detection mode

- test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/AlertCalculateIT.java
Lower the test threshold, the original threshold cannot be reached  within 10 minutes. 
None.
E2E test: `test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/AlertCalculateIT.java`
> fix(e2e): fix test threshold

- .github/workflows/e2e-test.yml
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/AbstractHostingAlertPlugin.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/model/DefaultHostingAlertPlugin.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/model/HostingAlert.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/model/HostingAlertList.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/IntegrationProductFacadeImpl.java
- test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/IntegrationPluginIT.java
- test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/bootstrap/ITSets.java
Closes #276 
Encapsulate multiple alarm rules configuration into an alarm hosting plugin, and install or remove it via the IntegrationPluginFacade interface. This approach is suitable for enterprise operation and maintenance scenarios, where alarm configurations can be unified and adjusted for all resources.
- `server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/AbstractHostingAlertPlugin.java` is the base class of the alarm plugin, which provides the common capabilities of the alarm plugin.
- `server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/model/DefaultHostingAlertPlugin.java`: is the default implementation of the alarm plugin.
Users can install the alert plugin via `/webapi/integration/plugin/create`
Unit test: …
> feat(home): alarm hosting plugin

- server/apm/apm-common/src/main/java/io/holoinsight/server/apm/common/constants/Const.java
- server/apm/apm-common/src/main/java/io/holoinsight/server/apm/common/model/specification/OtlpMappings.java
Closes #
This PR is to optimize the tags name mapping between `skywalking` and `opentelemetry`.
- Change the tags name mapping between `skywalking` and `opentelemetry` to dynamic judgment instead of hard-coded enumeration.
- By the way, some deprecated fields in the constant protocol were removed.
None.
> feat: optimize mappings between skywalking and opentelemetry

- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/compute/algorithm/ExtendConfig.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/ValueDownAbnormalDetect.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/ValueUpAbnormalDetect.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/data/load/AIAlarmLoadData.java
- server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/trigger/RuleConfig.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/IntegrationPluginFacadeImpl.java
- test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/IntegrationPluginIT.java
Closes #291 
We can improve the performance of our anomaly detection mechanism in intelligent alerting by only feeding the time series data to the algorithm, and avoiding the algorithm from making additional queries to the data source. This way, the algorithm can focus on the detection of anomalies in the time series data without incurring the additional overhead of querying the data source.
- Feeding data to algorithm in `server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/data/load/AIAlarmLoadData.java`
- Setting a threshold baseline for the algorithm's intervention can help reduce false positives, which can improve the performance of the intelligent alarm system. By establishing a threshold baseline, we can set a specific threshold for the algorithm to detect …
> feat(home): Feeding time series data to anomaly algorithm

- server/apm/apm-server/apm-service/src/main/java/io/holoinsight/server/apm/server/service/impl/TopologyServiceImpl.java
Closes #
To fix the bug brought by the previous pull request: incorrectly apply `serviceInstanceCalls` to the topology construction of the `endpoint`, resulting in an abnormal topology query.
The call loading of `service instance` or `endpoint` is abstracted as an interface, and the caller of topology construction will pass in different implementations.
None.
> fix: fix the topology exception of the endpoint

- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/event/AlertNotify.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AbstractUniformInspectRunningRule.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AlertTaskCompute.java
- server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/emuns/FunctionEnum.java
Closes #302 
Fix pql alert notification.
- Set `notifyDataInfoMap` to `NotifyDataInfos` for PQL alert in `server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/event/AlertNotify.java`.
- Build `notifyDataInfoMap` for PQL alert rule in `server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AbstractUniformInspectRunningRule.java`
None.
E2E test: `io.holoinsight.server.test.it.AlertRuleIT`
> fix(home): fix pql notification

- server/apm/apm-common/src/main/java/io/holoinsight/server/apm/common/model/specification/OtlpMappings.java
- server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/SpanEsStorage.java
- server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/postcal/PostCalMetricStorage.java
Closes #
This PR is to fix the mapping error of the `name` field that does not carry the prefix `resource.`.
- The mapping of the `name` field in OtlpMappings.java is handled separately.
- Fixed a typo in OtlpMappings.java.
- Tag keys are prefixed with SpanDO.attributes().
None.
> fix: fix name mapping

- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AlertTaskCompute.java
- server/home/home-alert/src/test/java/io/holoinsight/server/home/alert/service/calculate/AlertTaskComputeTest.java
Closes #317 
Fix the issue of alarm loss caused by concurrent calculation.
- Replace ArrayList with CopyOnWriteArrayList to solve the issue of concurrent writes to the list in `server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AlertTaskCompute.java`
None.
Unit test: `server/home/home-alert/src/test/java/io/holoinsight/server/home/alert/service/calculate/AlertTaskComputeTest.java`
> fix(home): fix alert concurrency

- .github/workflows/e2e-test.yml
- scripts/docker/Dockerfile
- scripts/docker/build.sh
Closes #
Before, we put the front-end build result `dist.zip` in the code base. This is a very bad practice. Now we put the front-end build result in another docker image, and then copy it to the holoinsight image to avoid pollution code library.
Local test
> refactor: copy front files from docker image

- server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/postcal/MetricsManager.java
Closes #
Fix the startup exception caused by the cache construction being later than the APM metrics initialization.
Loading APM metrics from the database is handled by try-catch and modified to execute regularly.
None.
> fix: fix db load metrics fail

- deploy/examples/k8s/base/collector.yaml
- deploy/examples/k8s/base/kustomization.yaml
- scripts/docker/Dockerfile
- server/common/common-service/src/main/java/io/holoinsight/server/common/security/InternalWebApiInterceptor.java
- server/gateway/gateway-core/pom.xml
- server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/trace/GatewayTraceConfiguration.java
- server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/trace/exporter/LocalTraceExporter.java
- test/scenes/common/base.yaml
- test/scenes/common/collector-config.yml
- test/scenes/scene-default/application.yaml
- test/scenes/scene-default/docker-compose.yaml
Closes #340
[holoinsight-collector](https://github.com/traas-stack/holoinsight-collector) is used to receive and forward trace data.
Holoinsight quick start example enables trace collection and storage capabilities.
- add skywalking into dockerfile
- add collector into quick start exmple
- example enables trace
- add LocalTraceExporter for trace
`./test/scenes/scene-default/up.sh`
> feat: add collector into quick start

- server/query/query-service/src/main/java/io/holoinsight/server/query/service/impl/DefaultQueryServiceImpl.java
Closes #
Use `datasource.name` as the metric name of the returned result when it is not blank.
Use `datasource.name` as the metric name of the returned result when it is not blank.
None.
> fix: fill metric names as datasource name if it is not blank

- server/common/common/src/main/java/io/holoinsight/server/common/JsonUtils.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictKey.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictType.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictUtil.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/common/ResponseUtil.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/config/RestAuthUtil.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/SysFacadeImpl.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/UserFacadeImpl.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/filter/Step2IdentityFilter.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/filter/Step3AuthFilter.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/filter/Step4AccessLogFilter.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/interceptor/MonitorScopeAuthInterceptor.java
Closes #369 
1. update response to filter authentication failure, the return result is in json format, use **_JsonResult.class_**.
_before request_
```
curl -i --location --request POST 'http://localhost:8080/webapi/v1/query' \
--header 'accessKey: example1' \
--header 'Content-Type: application/json' \
--data '{
"datasources": [
{
"metric": "k8s_pod_cpu_util",
"aggregator": "none",
"groupBy": [
],
"start": 1681375070000,
"end": 1681378670000
}
],
"tenant": "default"
}'
```
_before response_
```
HTTP/1.1 401
Server: nginx/1.20.1
Date: Fri, 14 Apr 2023 08:54:30 GMT
Content-Type: application/json;charset=ISO-8859-1
Content-Length: 112
Connection: keep-alive
{
"timestamp": "2023-04-14 16:44:59",
"status": 405,
"error": "Method Not Allowed",
"path": "/webapi/v1/query"
}
```
_after request_ …
> feat(home): update response to filter authentication failure

- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertNotifyHandler.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertSaveHistoryHandler.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/GetSubscriptionHandler.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/event/AlertEventService.java
Closes #374 
Using `continue` instead of `return`
- Using `continue` instead of `return` in `server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertNotifyHandler.java`
- Add stat logs.
None.
E2E test.
> fix(alert): fix alert lost

- scripts/docker/Dockerfile
- test/demo/demo-client/Dockerfile
- test/demo/demo-server/Dockerfile
Closes #376
- demo grpc version: 1.42.2
- demo skywalking agent version: 8.11.0
- skywalking agent 8.11.0 grpc server interceptor is  `io.grpc.internal.AbstractServerImplBuilder.addService`
- However, the interception point （`io.grpc.internal.AbstractServerImplBuilder.addService`）of grpc 1.42.2 version has changed, resulting in no interception of the grpc server service. 
- skywalking8.15.0 fixes this problem [skywalking pr](https://github.com/apache/skywalking-java/pull/457)
update demo skywalking agent version to 8.15.0
> feat: update skywalking agent version

- test/scenes/demo/docker-compose.yaml
- test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/LogMonitoring_1_log_IT.java
- test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/apm/ApmCallLinkDetailIT.java
Closes #
After updating the skywalking java agent version of demo-client and demo-server, some trace details changed, which leading to failed ITs. This PR fixes these failed ITs.
old is `Mysql/JDBI/Statement/executeQuery`
1. use `pull_policy: always` option for demo-client and demo-server
2. fix failed IT
3. set test_wait_log_monitoring_metric1 atMost wait to '5min' which is enough for a '5s log monitor task'
4. set test_wait_log_monitoring_metric2 atMost wait to '2min', because it will be completed soon when test_wait_log_monitoring_metric1 is executed successfully.
> test: fix failed ITs

- test/server-e2e-test/src/main/java/extensions/org/awaitility/core/ConditionFactory/ConditionFactoryExtension.java
- test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AlertCalculateIT.java
- test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AlertRuleIT.java
- test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AppMonitoringIT.java
- test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/CeresdbPqlMonitoringIT.java
- test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/IntegrationPluginIT.java
- test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/LogMonitoringIT.java
- test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/LogMonitoring_1_log_IT.java
- test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/MetaVMIT.java
- test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/MetricMonitoringIT.java
- test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/TaskIT.java
- test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/apm/ApmAppMetricStatIT.java
- test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/apm/ApmCallLinkDetailIT.java
- test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/apm/ApmCallLinkIT.java
- test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/apm/ApmTopologyIT.java
Closes #
When use `ConditionFactory#untilAsserted(ThrowingRunnable)`, only `AssertionError`
will be treated as expected errors and then retry tests. Other exceptions will lead to test
failure.
But it is also very common to encounter the following exceptions when using `rest-assured`.
These exceptions should be treated as expected errors too.
- NullPointerException
- org.apache.http.NoHttpResponseException
This PR add a method which treats all exceptions as retryable errors.
This PR add a method which treats all exceptions as retryable errors.
> test: treat all exceptions as retryable errors

- server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/SpanEsStorage.java
- server/query/query-grpc-gen/src/main/java/io/holoinsight/server/query/grpc/QueryProto.java
- server/query/query-grpc-gen/src/main/proto/query_proto.proto
- server/query/query-service/src/main/java/io/holoinsight/server/query/service/impl/DefaultQueryServiceImpl.java
Closes #
- Add query parameter termParams to the apm metadata query function to expand query capabilities
- Set default service instance for trace query(service instance corresponds to resource.host.name in otel sdk, and otel sdk will not collect resource.host.name in versions below 1.19.0, so need to set a default value to avoid query errors)
> fix(apm): fix trace query

- scripts/docker/Dockerfile
Closes #
Currently we have some gRPC methods calling `onNext` and `onComplete` asynchronously in another thread.  
Without using SkyWalking java agent, everything is fine.
When using SkyWalking java agent, these methods fails because `onComplete` will throw an exception caused by SkyWalking internal.
I think this is because the async behavior of our gRPC service impl.
According to [this doc](https://github.com/apache/skywalking-java/blob/main/docs/en/setup/service-agent/java-agent/Application-toolkit-trace-cross-thread.md) we should manually pass the SkyWalking internal tracing context to new thread.
I will try the doc and fix the bug in another PR.
Disable skywalking grpc plugin
> fix: disable SkyWalking gRPC plugin

- server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/dto/conf/CustomPluginConf.java
- server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/dto/conf/Translate.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/GaeaSqlTaskUtil.java
- server/registry/registry-model/src/main/java/io/holoinsight/server/registry/model/Elect.java
- server/registry/registry-model/src/main/java/io/holoinsight/server/registry/model/Where.java
Closes #407 
1. support translation capabilities of log monitoring
func list:
- substringV1
```
doc: Cut out the substring 
params: 
- begin: begin must be >=0 
- end: If end==-1, the match ends 
- emptyIfError: boolean Specifies whether to return an empty string if an error (such as an overstep) occurs during the partitioning process
```
- appendV1
```
doc: Appends content to a string 
params: 
- value: "additional content ", 
- appendIfMissing: boolean: Default false. If true, appended only when there is no $value at the end
```
- mappingV1
```
doc: Mapping, equivalent to map.getOrDefault(str, defaultValue) in Java 
params: 
- mappings: A map with map<string, string> 
- defaultValue: indicates the default value
```
- constV1
```
doc: Returns a constant 
params: 
- value: A constant, …
```
> feat(home): logmonitor adds translation capabilities

- server/extension/extension-storage-ceresdbx/src/main/java/io/holoinsight/server/extension/ceresdbx/CeresdbxMetricStorage.java
Closes #397 
The query time range for ceresdb should be [begin, end] instead of  [begin, end).
> fix: fix ceresdb end timestamp

- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/common/TimeRangeUtil.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/event/AlertNotify.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/event/AlertNotifyRequest.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertNotifyHandler.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertSaveHistoryHandler.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/CacheAlertTask.java
- server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/converter/AlarmHistoryDetailConverter.java
- server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlarmHistoryDetailDTO.java
- server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlertTemplateField.java
- server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/InspectConfig.java
- server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/NotificationTemplate.java
- server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/TemplateValue.java
- server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/trigger/AlertHistoryDetailExtra.java
Closes #411 
Alert supports including log samples in alert history and notification.
- Alert handler will try to query log sample in `server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertSaveHistoryHandler.java` if the log analysis is enable in the logmonitor datasource.
If the `LOG_CONTENT` is included in the DingTalk alarm template, the alarm message will carry the log sampling content.
Supplement later.
> feat(home): alert log analysis

- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/AlarmHistoryDetailService.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlarmHistoryDetailServiceImpl.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmHistoryDetailFacadeImpl.java
- test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AlertRuleIT.java
Closes #
Provide an interface to return the quantity of alert history detail in a time-series data format, which can be used for displaying event monitoring dashboard on the frontend.
- Add `/webapi/alarmHistoryDetail/countTrend ` in `server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmHistoryDetailFacadeImpl.java`
None.
E2E test: `test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AlertRuleIT.java`
> feat(home): alert history detail query

- server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/collecttarget/CollectTargetStorage.java
Closes #
When a statefulset pod move from one node to another. Its namespace and podName doesn't change.
In the holoinsight server side, the pod meta uk is calculated by namespace, podName ...
So its uk stays the same.
In `io.holoinsight.server.registry.core.collecttarget.CollectTargetMaintainer#maintainTemplate1`, when statefulset pod move to another node, its `refAgent` is changed, and leading to a target update, which finally calls `io.holoinsight.server.registry.core.collecttarget.CollectTargetStorage#batchPut`.
In `batchPut`, it didn't delete the old target index `byAgent`. So the old `refAgent` index still owns the target, which leads to redundant tasks running on wrong agent.
- Remove redundant targets
> fix: remove redundant targets

- server/apm/apm-common/src/main/java/io/holoinsight/server/apm/common/model/specification/OtlpMappings.java
- server/apm/apm-common/src/main/java/io/holoinsight/server/apm/common/model/specification/sw/ServiceRelation.java
- server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/SpanMetricEsStorage.java
- server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/model/ServiceRelationDO.java
- server/apm/apm-server/apm-engine/src/main/resources/metrics/metrics.json
- server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/builder/RPCTrafficSourceBuilder.java
- server/query/query-service/src/main/java/io/holoinsight/server/query/service/impl/DefaultQueryServiceImpl.java
Closes #
This PR is to do special processing for APM-related meta-information queries, so as to correctly return relevant information.
- Modify the `querySchema` and `queryMetrics` functions to do special processing for APM metrics.
- Corrected grouping of `apm-component*` related metrics.
Users can now correctly query the meta information of APM indicators.
> fix: fix APM metrics meta query

- server/extension/extension-common-flyway/src/main/resources/db/migration/V7__230427_ADD_meta_dim_data_TABLE.sql
- server/extension/extension-storage-ceresdbx/src/main/java/io/holoinsight/server/extension/ceresdbx/CeresdbxMetricStorage.java
- server/meta/meta-boot/src/main/java/io/holoinsight/server/meta/bootstrap/MetaMongoDBConfig.java
- server/meta/meta-bootstrap/src/main/resources/config/application.yaml
- server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/MetaServiceConfiguration.java
- server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/common/FilterUtil.java
- server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/service/DBCoreService.java
- server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/service/MongoDataCoreService.java
- server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/service/SqlDataCoreService.java
- server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/service/grpc/DataServiceGrpcImpl.java
- server/meta/meta-core/src/main/java/io/holoinsight/server/meta/core/web/controller/AdminController.java
- server/meta/meta-dal/pom.xml
- server/meta/meta-dal/src/main/java/io/holoinsight/server/meta/dal/service/mapper/MetaDataMapper.java
- server/meta/meta-dal/src/main/java/io/holoinsight/server/meta/dal/service/model/MetaData.java
- server/meta/meta-dal/src/main/resources/mybatis/mybatis-config.xml
- server/meta/meta-dal/src/main/resources/sqlmap/MetaDataMapper.xml
- server/meta/meta-facade/src/main/java/io/holoinsight/server/meta/facade/service/DataClientService.java
- server/meta/meta-facade/src/main/java/io/holoinsight/server/meta/facade/service/DimCookie.java
- server/meta/meta-facade/src/main/java/io/holoinsight/server/meta/facade/service/impl/DataClientServiceImpl.java
- server/meta/meta-facade/src/main/java/io/holoinsight/server/meta/facade/service/impl/LocalDataClientService.java
- server/meta/meta-proto/src/main/proto/DataService.proto
Closes #452 
Support for using MySQL to store metadata
To verify the ability to write metadata to MySQL, it will be temporarily validated by writing to both MongoDB and MySQL simultaneously. 
local test
> feat: Support for using MySQL to store metadata

- server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/SpanEsStorage.java
- server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/storage/SpanStorage.java
- server/apm/apm-server/apm-service/src/main/java/io/holoinsight/server/apm/server/service/TraceService.java
- server/apm/apm-server/apm-service/src/main/java/io/holoinsight/server/apm/server/service/impl/TraceServiceImpl.java
- server/apm/apm-server/apm-web/src/main/java/io/holoinsight/server/apm/web/impl/TraceApiController.java
Closes #
This PR is to optimize the implementation of `queryTrace` API: support the transfer of conditions such as tenant and time interval that can be used for query pruning to the underlying storage engine.
Functions related to `queryTrace` can pass in three additional fields: `tenant`, `start`, `end`, and build query requests for the underlying storage engine accordingly.
Users can get better response performance when querying a single trace.
> feat: query trace with tenant and time range

- server/apm/apm-server/apm-service/src/main/java/io/holoinsight/server/apm/server/service/impl/ApmMetricMaterializer.java
Closes #
Limit the queue length of the APM indicator materialized thread pool to avoid HoloInsight FGC when the performance of the downstream engine deteriorates.
Limit the queue size of ApmMaterializer to 4096.
None.
> feat: limit queue size

- server/home/home-boot/src/main/java/io/holoinsight/server/home/bootstrap/HoloinsightHomeConfiguration.java
- server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/QueryClientService.java
- server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/RequestContextAdapter.java
- server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/RequestContextAdapterImpl.java
Closes #487 
- Provide the interface that change the query tenant in alert query.
- Add `server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/RequestContextAdapter.java`
None.
None.
> feat: tenant adaptation in alarm query

- server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/utils/EsGsonUtils.java
- test/scenes/common/base.yaml
- test/scenes/scene-default/application.yaml
- test/scenes/scene-default/docker-compose.yaml
Closes #
Use [Tatris](https://github.com/tatris-io/tatris) as the storage engine of APM in test scenes.
1. Use [Tatris](https://github.com/tatris-io/tatris) as the storage engine of APM in test scenes.
2. Fix the data type handling exception of `_timestamp` field.
None.
I have verified that the HoloInsight service can be started normally through `up.sh`.
> feat: tatris scene

- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/event/AlertNotify.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/event/AlertNotifyRequest.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertNotifyHandler.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertSaveHistoryHandler.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/converter/DoConvert.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/event/alertManagerEvent/AlertManagerBuildMsgHandler.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/CacheAlertTask.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/coordinator/CoordinatorService.java
- server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/InspectConfig.java
- server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/TemplateValue.java
- server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/trigger/AlertHistoryDetailExtra.java
- test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AlarmMetricFacadeIT.java
- test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/IntegrationGeneratedFacadeIT.java
Closes #532
Check whether the metric is configured with log sampling during the alarm notification process. If log sampling is configured, attempt to query the log sampling result and include it in the notification result.
- Check whether the metric is configured with log sampling `server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/CacheAlertTask.java`
- Try to query the log sampling result `server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertSaveHistoryHandler.java`
- Add black list to avoid the alert task assigned in specified servers `server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/coordinator/CoordinatorService.java`
None.
> feat(home): log sample alert

- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/UserinfoServiceImpl.java
Closes #
Avoid empty collection in sql `IN`, so we should check uid list first.
None.
> fix(home): avoid empty collection in sql `IN`

- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/GetSubscriptionHandler.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/BaseFunction.java
- server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/RequestContextAdapter.java
- server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/RequestContextAdapterImpl.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/AlertSubscribeService.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlarmHistoryDetailServiceImpl.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlarmHistoryServiceImpl.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlertDingDingRobotServiceImpl.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlertGroupServiceImpl.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlertRuleServiceImpl.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlertSubscribeServiceImpl.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmDingDingRobotFacadeImpl.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmGroupFacadeImpl.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmRuleFacadeImpl.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmSubscribeFacadeImpl.java
- server/home/home-web/src/test/java/io/holoinsight/server/home/web/controller/AlarmRuleFacadeImplTest.java
Closes #
In some deployment scenarios, it is necessary to implement alarm subscription and notification across tenants. Therefore, the logic of setting tenant conditions needs to be abstracted into an interface, which may have different implementations in different scenarios.
- Interface for setting tenant conditions `server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/RequestContextAdapter.java`
None.
> feat(home): alert subscribe across tenants 

- server/apm/apm-common/src/main/java/io/holoinsight/server/apm/common/constants/Const.java
- server/apm/apm-common/src/main/java/io/holoinsight/server/apm/common/model/query/TraceTree.java
- server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/SpanEsStorage.java
- server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/storage/SpanStorage.java
- server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/analysis/ServiceErrorAnalysis.java
- server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/analysis/SlowSqlAnalysis.java
- server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/common/PublicAttr.java
- server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/common/TransformAttr.java
- server/apm/apm-server/apm-receiver/src/main/java/io/holoinsight/server/apm/receiver/trace/SpanHandler.java
- server/apm/apm-server/apm-service/src/main/java/io/holoinsight/server/apm/server/service/TraceService.java
- server/apm/apm-server/apm-service/src/main/java/io/holoinsight/server/apm/server/service/impl/TraceServiceImpl.java
- server/apm/apm-server/apm-web/src/main/java/io/holoinsight/server/apm/web/TraceApi.java
- server/apm/apm-server/apm-web/src/main/java/io/holoinsight/server/apm/web/impl/TraceApiController.java
- server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/QueryClientService.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/TraceQueryFacadeImpl.java
- server/query/query-common/src/main/java/io/holoinsight/server/query/common/convertor/ApmConvertor.java
- server/query/query-grpc-gen/src/main/java/io/holoinsight/server/query/grpc/QueryProto.java
- server/query/query-grpc-gen/src/main/java/io/holoinsight/server/query/grpc/QueryServiceGrpc.java
- server/query/query-grpc-gen/src/main/proto/query_proto.proto
- server/query/query-server/src/main/java/io/holoinsight/server/query/server/controllers/QueryController.java
- server/query/query-server/src/main/java/io/holoinsight/server/query/server/rpc/QueryGrpcService.java
- server/query/query-service/src/main/java/io/holoinsight/server/query/service/QueryService.java
- server/query/query-service/src/main/java/io/holoinsight/server/query/service/apm/ApmAPI.java
- server/query/query-service/src/main/java/io/holoinsight/server/query/service/impl/DefaultQueryServiceImpl.java
Closes #
This pr is to make holoinsight single ratio trace function compatible with sofatracer.
- add new webapi `/webapi/v1/trace/query/traceTree`， returns the tree trace structure, the front end only needs to render, no need to build a tree relationship
- Holoinsigth stores the real traceId, you can use the traceId printed by the agent to search for relevant traces in holoinsight
> feat: sofatracer

- server/common/common-dao/src/main/java/io/holoinsight/server/common/dao/entity/MetricInfo.java
- server/common/common-dao/src/main/java/io/holoinsight/server/common/dao/entity/dto/MetricInfoDTO.java
- server/extension/extension-common-flyway/src/main/resources/db/migration/V14__230801_ADD_metricinfo_COLUMN.sql
- server/home/home-task/src/main/java/io/holoinsight/server/home/task/AbstractMetricCrawlerBuilder.java
- server/home/home-task/src/main/java/io/holoinsight/server/home/task/crawler/ApmMetricCrawlerBuilder.java
- server/home/home-task/src/main/java/io/holoinsight/server/home/task/crawler/JvmMetricCrawlerBuilder.java
- server/home/home-task/src/main/java/io/holoinsight/server/home/task/crawler/MysqlMetricCrawlerBuilder.java
- server/home/home-task/src/main/java/io/holoinsight/server/home/task/crawler/PortCheckMetricCrawlerBuilder.java
- server/home/home-task/src/main/java/io/holoinsight/server/home/task/crawler/SystemMetricCrawlerBuilder.java
Closes #
Add `storage_tenant` in `metric_info` table to accommodate different storage media.
- Add `storageTenant` in `server/common/common-dao/src/main/java/io/holoinsight/server/common/dao/entity/MetricInfo.java`
- Add `server/extension/extension-common-flyway/src/main/resources/db/migration/V14__230801_ADD_metricinfo_COLUMN.sql`
None.
> feat(home): add storage_tenant column in metric_info table

- server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/dto/conf/Rule.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/GaeaSqlTaskUtil.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/MetaService.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/TenantInitService.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/DefaultTenantInitServiceImpl.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/ula/MonitorULA.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/ula/ULA.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/ula/ULAFacade.java
- server/home/home-task/src/main/java/io/holoinsight/server/home/task/impl/TenantAppMetaSyncTask.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/MetaFacadeImpl.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/filter/Step3AuthFilter.java
- test/scenes/common/log-json-generator.py
- test/scenes/scene-default/after.sh
- test/scenes/scene-default/docker-compose.yaml
Closes #
1. Log monitoring supports json logs，the parse type must be set to **_json_**
example:
```
{"time":"2023-03-23 16:19:01","level":"INFO","cost":1}
```
```
{
"select": {
"values": [
{
"as": "count",
"agg": "count"
},
{
"as": "cost_sum",
"agg": "sum",
"elect": {
"type": "refName",
"refName": {
"name": "$.cost"
}
}
}
]
},
"from": {
"type": "log",
"log": {
"path": [
{
"type": "path",
"pattern": "/tmp/1.log"
}
],
"charset": "utf-8",
"parse": {
"type": "json"
},
"time": {
"_doc": "将 type 设置成 processTime 表示使用 '处理时间' 作为时间戳 ",
"type": "elect",
"elect": {
"type": "refName",
"refName": {
"name": "$.time"
}
},
"format": "golangLayout",
"layout": "2006-01-02 15:04:05"
}
}
},
"where": {},
"groupBy": {
"maxKeys": -1,
"groups": [
{
"name": "level",
"elect": {
"type": "refName",
"refName": { …
```
> feat(home): Log monitoring supports json logs

- server/apm/apm-common/src/main/java/io/holoinsight/server/apm/common/constants/Const.java
- server/apm/apm-common/src/main/java/io/holoinsight/server/apm/common/model/query/TraceTree.java
- server/apm/apm-common/src/main/java/io/holoinsight/server/apm/common/model/specification/sw/Span.java
- server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/SpanEsStorage.java
- server/query/query-common/src/main/java/io/holoinsight/server/query/common/convertor/ApmConvertor.java
- server/query/query-grpc-gen/src/main/java/io/holoinsight/server/query/grpc/QueryProto.java
- server/query/query-grpc-gen/src/main/proto/query_proto.proto
Closes #
Mesh Span is used as supplementary information and does not participate in the construction of the trace tree.
This modification is compatible with the mosn span collected by sofatracer.
> fix: compatible with mesh spans

- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/TraceAgentFacadeImpl.java
> fix: fix trace agent

- server/apm/apm-boot/src/main/java/io/holoinsight/server/apm/bootstrap/HoloinsightApmConfiguration.java
- server/apm/apm-common/src/main/java/io/holoinsight/server/apm/common/model/query/Event.java
- server/apm/apm-server/apm-core/src/main/java/io/holoinsight/server/apm/core/installer/ModelInstallManager.java
- server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/HoloinsightEsConfiguration.java
- server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/EventEsStorage.java
- server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/utils/ApmGsonUtils.java
- server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/model/EventDO.java
- server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/storage/EventStorage.java
- server/apm/apm-server/apm-service/src/main/java/io/holoinsight/server/apm/server/service/EventService.java
- server/apm/apm-server/apm-service/src/main/java/io/holoinsight/server/apm/server/service/impl/EventServiceImpl.java
- server/apm/apm-server/apm-web/src/main/java/io/holoinsight/server/apm/web/ApmWebConfiguration.java
- server/apm/apm-server/apm-web/src/main/java/io/holoinsight/server/apm/web/EventApi.java
- server/apm/apm-server/apm-web/src/main/java/io/holoinsight/server/apm/web/impl/EventApiController.java
Closes #
This pr implements the es storage event and provides a query interface,
the event is first added to the apm module.
Event data model，In order to make the design more general, only a few necessary fields are provided, and other additional fields should be added to `tags`
```
private String tenant;
private String id;
private String name;
private String type;
private long timestamp;
private Map<String, String> tags; 
```
Insert interface: io.holoinsight.server.apm.server.service.EventService.insert
Query interface: io.holoinsight.server.apm.server.service.EventService.queryEvents
> feat: storage event

- server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/QueryClientService.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/TraceQueryFacadeImpl.java
- server/query/query-common/src/main/java/io/holoinsight/server/query/common/convertor/ApmConvertor.java
- server/query/query-grpc-gen/src/main/java/io/holoinsight/server/query/grpc/QueryProto.java
- server/query/query-grpc-gen/src/main/java/io/holoinsight/server/query/grpc/QueryServiceGrpc.java
- server/query/query-grpc-gen/src/main/proto/query_proto.proto
- server/query/query-server/src/main/java/io/holoinsight/server/query/server/controllers/QueryController.java
- server/query/query-server/src/main/java/io/holoinsight/server/query/server/rpc/QueryGrpcService.java
- server/query/query-service/src/main/java/io/holoinsight/server/query/service/QueryService.java
- server/query/query-service/src/main/java/io/holoinsight/server/query/service/apm/ApmAPI.java
- server/query/query-service/src/main/java/io/holoinsight/server/query/service/impl/DefaultQueryServiceImpl.java
Closes #
Add a api for query events.
```
curl --location --request POST 'http://127.0.0.1:8080/webapi/v1/trace/events' \
--header 'Content-Type: application/json' \
--data-raw '
{
"tenant": "xx",
"start": 1693384444953,
"end": 1693384444955,
"termParams": {
"xx": "xx"
}
}'
```
> feat: event query api

- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/MetricInfoCheckService.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/MetricInfoCheckServiceImpl.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/MetricInfoFacadeImpl.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java
- server/home/home-web/src/test/java/io/holoinsight/server/home/web/controller/QueryFacadeImplTest.java
Closes #
To prevent SQL injection, restrict the query types to only allow querying `count(1)` or `approx_distinct`.
- Give restriction in `server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java`
none.
> fix: sql injection

- server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/QueryClientService.java
Closes #
Fix grpc limit of `io.holoinsight.server.home.common.service.QueryClientService#queryData` to 40MB.
> fix: fix grpc limit

- server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/conf/AggTask.java
- server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/conf/AggTaskVersion.java
- server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/conf/FillZero.java
- server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/AggTaskExecutor.java
- server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/PartitionProcessor.java
- server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/state/AggTaskState.java
- server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/state/AggWindowState.java
Closes #
When the agg task has no data at all in a certain period, it will not produce any output.
A certain combined dimension of the agg task appears in a certain time window, but may not appear again for a period of time.
Some product layer scenarios may expect the agg layer to have "fill-zero" capabilities. If there is no original data, a zero value will be filled in.
Agg supports 'fill-zero' when emitting.
> feat: agg fill zero

- server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/kafka/KafkaProducerHealthChecker.java
- server/agg/agg-dispatcher/src/main/java/io/holoinsight/server/agg/v1/dispatcher/AggDispatcher.java
Closes #
When kafka is unhealthy, `kafkaProducer.send(record)` and `kafkaProducer.send(record, callback)` will block for ProducerConfig.MAX_BLOCK_MS_CONFIG millis.
This will cause the thread to block. I would prefer that we fail quickly when kafka fails.
- Add kafka producer healthchecker.  When kafka is detected to be unavailable, send is no longer called.
> feat: add kafka producer healthchecker

- server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/AggTaskExecutor.java
- server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/Executor.java
- server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/PartitionProcessor.java
- server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/state/PartitionState.java
Closes #
When agg is restored from a very old state, the kafka message corresponding to the restored offset may have been deleted.
At this time, a lot of empty windows may be created in the `io.holoinsight.server.agg.v1.executor.executor.AggTaskExecutor#maybeFillZero` method, causing OOM.
Check the validity of the restored offset, and clear the status if it is not legal.
> fix: restored from too old state

- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/GetSubscriptionHandler.java
Closes #
In the case that there are multiple alarm subscribe records, the older ones may be overrode by new one.
Fix it.
> fix: get subscription for multiple alarm subscribers

- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmDingDingRobotFacadeImpl.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/LevelAuthorizationCheck.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/custom/AlarmDingDingRobotFacadeImplChecker.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/custom/AlertTemplateFacadeImplChecker.java
> fix: check userid in dingdingrobot facade

- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/GatewayService.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlertTemplateFacadeImpl.java
> fix: alert template

- server/home/home-boot/src/main/java/io/holoinsight/server/home/bootstrap/HoloinsightHomeConfiguration.java
- server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/RequestContextAdapter.java
- server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/RequestContextAdapterImpl.java
- server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/dto/conf/CollectMetric.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/AggTaskUtil.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/GaeaSqlTaskUtil.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/listener/CustomPluginUpdateListener.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlarmMetricServiceImpl.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlertRuleServiceImpl.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/CustomPluginServiceImpl.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/ula/MonitorULA.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/ula/ULA.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/ula/ULAFacade.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmMetricFacadeImpl.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmRuleFacadeImpl.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/UserOpLogFacadeImpl.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/filter/Step3AuthFilter.java
> refactor: add monitorparams in ula

- server/common/common-dao/src/main/java/io/holoinsight/server/common/dao/entity/MonitorInstance.java
- server/extension/extension-common-flyway/src/main/resources/db/migration/V33__240226_ADD_monitor_instance_COLUMN.sql
> feat: add instance info field

- server/common/common-service/src/main/java/io/holoinsight/server/common/service/MetricInfoService.java
- server/common/common-service/src/main/java/io/holoinsight/server/common/service/MetricInfoServiceImpl.java
- server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlertRuleExtra.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/AlertRuleService.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlertRuleServiceImpl.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/CustomPluginFacadeImpl.java
> refactor: add md5 in alarmRule

- server/home/home-boot/src/main/java/io/holoinsight/server/home/bootstrap/HoloinsightHomeConfiguration.java
- server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/RequestContextAdapter.java
- server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/RequestContextAdapterImpl.java
- server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/query/QueryDetailResponse.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlertRuleServiceImpl.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/UserOpLogServiceImpl.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/UserFavoriteFacadeImpl.java
> feat: alert rule template

- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/AlertGroupService.java
- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlertGroupServiceImpl.java
> fix: alarm group query by workspace

- server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/conf/Extension.java
- server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/PartitionProcessor.java
- server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/XAggTask.java
Closes #
When an AggTask update is found, discard the intermediate calculation results of
the current cycle. Doing so allows you to immediately update the day-level tasks instead of
waiting until the next day to take effect. But the disadvantage is that the intermediate
state will be lost and the data will be calculated from zero.
> feat: support discarding intermediate data when aggtask is updated

- server/common/common/src/main/java/io/holoinsight/server/common/springboot/ConditionalOnRole.java
- server/common/common/src/main/java/io/holoinsight/server/common/springboot/ConditionalOnRoleCondition.java
Closes #
The original semantics of ConditionOnRole is that it takes effect when any role is activated.
Now there is a new parameter any, which is used to control the relationship between roles, whether it is 'any' or 'and'.
> refactor: ConditionalOnRole

- server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlertGroupServiceImpl.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/custom/AlarmRuleLevelAuthorizationChecker.java
> fix: checker

- server/common/common/src/main/java/io/holoinsight/server/common/threadpool/CommonThreadPools.java
- server/otlp/otlp-server/src/main/java/io/holoinsight/server/otlp/server/HoloInsightOTLPAutoConfiguration.java
- server/otlp/otlp-server/src/main/java/io/holoinsight/server/otlp/server/OTLPGrpcServer.java
- server/otlp/otlp-server/src/main/java/io/holoinsight/server/otlp/server/OTLPWebController.java
- server/otlp/otlp-server/src/main/java/io/holoinsight/server/otlp/server/OtlpConfig.java
Closes #
otlp use its own thread pool
> refactor: otlp use its own thread pool

- server/apm/apm-server/apm-core/src/main/java/io/holoinsight/server/apm/core/ApmConfig.java
- server/apm/apm-server/apm-service/src/main/java/io/holoinsight/server/apm/server/service/impl/ApmMetricMaterializer.java
- server/common/common-service/src/main/java/io/holoinsight/server/common/ctl/ProductCtlServiceImpl.java
- server/common/common-service/src/main/java/io/holoinsight/server/common/service/SuperCache.java
- server/common/common-service/src/main/java/io/holoinsight/server/common/service/SuperCacheService.java
> refactor(home): add resourceKeys in supercache

- server/agg/agg-executor-bootstrap/src/main/resources/config/application.yaml
- server/all-in-one/all-in-one-bootstrap/pom.xml
- server/all-in-one/all-in-one-bootstrap/src/main/resources/log4j2.xml
- test/scenes/common/base.yaml
- test/scenes/common/status.sh
- test/scenes/scene-default/application.yaml
- test/scenes/scene-default/docker-compose.yaml
> chore: add kafka to docker compose yaml

- server/common/common-service/src/main/java/io/holoinsight/server/common/config/EnvironmentProperties.java
- server/extension/extension-storage-ceresdbx/pom.xml
- server/extension/extension-storage-ceresdbx/src/main/java/io/holoinsight/server/extension/ceresdbx/CeresdbxClientManager.java
- server/extension/extension-storage-ceresdbx/src/main/java/io/holoinsight/server/extension/ceresdbx/HoloinsightCeresdbxConfiguration.java
> feat: address zone

- server/common/common/src/main/java/io/holoinsight/server/common/Pair.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmSubscribeFacadeImpl.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/ParameterSecurityService.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/ParameterSecurityServiceImpl.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/custom/AlarmSubscribeFacadeImplChecker.java
- test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AlarmSubscribeFacadeIT.java
> feat: alarm subscribe checker

- server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/query/KeyResult.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmDingDingRobotFacadeImpl.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmRuleFacadeImpl.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/FolderFacadeImpl.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/ParameterSecurityService.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/ParameterSecurityServiceImpl.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/custom/AlarmRuleLevelAuthorizationChecker.java
- test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/FolderFacadeIT.java
- test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/LogMonitoringFolderIT.java
> feat: checker

- server/common/common-service/src/main/java/io/holoinsight/server/common/service/AlertRuleService.java
- server/common/common-service/src/main/java/io/holoinsight/server/common/service/SuperCache.java
- server/common/common-service/src/main/java/io/holoinsight/server/common/service/SuperCacheService.java
- server/common/common-service/src/main/java/io/holoinsight/server/common/service/impl/AlertRuleServiceImpl.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/custom/AlarmRuleLevelAuthorizationChecker.java
- server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/agent/AgentService.java
- server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/grpc/RegistryServiceForAgentImpl.java
> fix: agentId stat

- server/common/common-service/src/main/java/io/holoinsight/server/common/service/SuperCache.java
- server/common/common-service/src/main/java/io/holoinsight/server/common/service/SuperCacheService.java
- server/home/home-web/src/main/java/io/holoinsight/server/home/web/security/custom/AlarmRuleLevelAuthorizationChecker.java
> feat: rm metric type cache

- server/common/common-dao/src/main/java/io/holoinsight/server/common/dao/entity/AlarmCountable.java
- server/common/common-dao/src/main/java/io/holoinsight/server/common/dao/entity/Folder.java
- server/common/common-dao/src/main/java/io/holoinsight/server/common/dao/entity/FolderPath.java
- server/common/common-dao/src/main/java/io/holoinsight/server/common/dao/entity/FolderPaths.java
- server/common/common-service/src/main/java/io/holoinsight/server/common/service/AlarmHistoryDetailService.java
- server/common/common-service/src/main/java/io/holoinsight/server/common/service/AlarmHistoryService.java
- server/common/common-service/src/main/java/io/holoinsight/server/common/service/impl/AlarmHistoryDetailServiceImpl.java
- server/common/common-service/src/main/java/io/holoinsight/server/common/service/impl/AlarmHistoryServiceImpl.java
- server/extension/extension-common-flyway/src/main/resources/db/migration/V34__240920_ADD_custom_plugin_COLUMN.sql
- server/extension/extension-common-flyway/src/main/resources/db/migration/V35__240920_ADD_folder_COLUMN.sql
- server/extension/extension-common-flyway/src/main/resources/db/migration/V36__241011_ADD_folder_AND_custom_COLUMN.sql
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/event/WebhookInfo.java
- server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/GetSubscriptionHandler.java
- server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/CustomPlugin.java
- server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/dto/CustomPluginDTO.java
- server/home/home-task/src/main/java/io/holoinsight/server/home/task/MonitorAlarmRrdTask.java
- server/home/home-task/src/main/java/io/holoinsight/server/home/task/MonitorAlarmRrdTaskJob.java
Closes #
1. add alarm rrd in logmonitor
2. add global webhook of tenant
> feat: add alarm rrd
